### ISSUE TITLE
[Bug]: Hop Web clipboard access is not available for non-localhost servers

### ISSUE THREAD

**Issue by mattcasters** [apache/hop#1897]
### Apache Hop version?

2.2.0

### Java version?

openjdk version "11.0.17" 2022-10-18

### Operating system

Docker

### What happened?

When copying to the clipboard on hop web we see the following error appear:

`There was an unexpected error while copying data to the clipboard.
org.eclipse.swt.SWTError: Cannot set data in clipboard
	at org.eclipse.swt.dnd.DND.error(DND.java:263)
	at org.eclipse.swt.dnd.DND.error(DND.java:219)
	at org.eclipse.swt.dnd.Clipboard.setContents(Clipboard.java:272)
	at org.apache.hop.ui.core.gui.GuiResource.toClipboard(GuiResource.java:1296)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineClipboardDelegate.toClipboard(HopGuiPipelineClipboardDelegate.java:62)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineClipboardDelegate.copySelected(HopGuiPipelineClipboardDelegate.java:296)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.copySelectedToClipboard(HopGuiPipelineGraph.java:5134)
	at org.apache.hop.ui.hopgui.HopGui.menuEditCopySelected(HopGui.java:880)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.ui.core.gui.GuiMenuWidgets.executeMenuItem(GuiMenuWidgets.java:174)
	at org.apache.hop.ui.core.gui.GuiMenuWidgets.lambda$addMenuWidgets$0(GuiMenuWidgets.java:122)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.MenuItem.handleAcceleratorActivation(MenuItem.java:687)
	at org.eclipse.swt.widgets.AcceleratorBinding.handleEvent(AcceleratorBinding.java:35)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1819)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:685)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
	at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1216)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1197)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1172)
	at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
`

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Web

**Comment by hlcianfagna** [comment]
Still an issue with `docker.io/apache/hop-web:latest` (2.9.0)

**Comment by hansva** [comment]
This is no longer an issue.
You do need the website to be safe (e.g. have valid certificates) or be running on localhost to enable copy/paste in modern browsers.
