### ISSUE TITLE
[Bug]: ArrayIndexOutOfBoundsException on Concat All Fields

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#1909]
### Apache Hop version?

2.1.0

### Java version?

Adaptive JDK 11.04

### Operating system

Windows

### What happened?

When you want to concatenate ALL input fields you should be able to specify no fields in the fields list and all fields will be concatenated by default. In Hop this causes the  following error:

2022/10/17 10:36:32 - Concat Fields.0 - ERROR: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
2022/10/17 10:36:32 - Concat Fields.0 -     at org.apache.hop.pipeline.transforms.concatfields.ConcatFields.putRowFastDataDump(ConcatFields.java:171)
2022/10/17 10:36:32 - Concat Fields.0 -     at org.apache.hop.pipeline.transforms.concatfields.ConcatFields.processRow(ConcatFields.java:107)
2022/10/17 10:36:32 - Concat Fields.0 -     at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:58)
2022/10/17 10:36:32 - Concat Fields.0 -     at java.base/java.lang.Thread.run(Thread.java:829)

In PDI 8.X this works fine. See the screenshot below

![image](https://user-images.githubusercontent.com/1270945/205701456-6b37ecf1-820b-438f-b7ae-49c5a5e156ef.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
Works in 2.3
