### ISSUE TITLE
[Bug]: Import success dialog turned into an error

### ISSUE THREAD

**Issue by mattcasters** [apache/hop#2028]
### Apache Hop version?

2.2.0

### Java version?

openjdk version "11.0.17" 2022-10-18

### Operating system

Linux

### What happened?

If you do an import of Kettle transformations and jobs into a target folder or project you get the following null pointer exception:

`java.lang.NullPointerException
        at org.apache.hop.ui.pipeline.transform.BaseTransformDialog.positionBottomButtons(BaseTransformDialog.java:356)
        at org.apache.hop.ui.pipeline.transform.BaseTransformDialog.positionBottomButtons(BaseTransformDialog.java:329)
        at org.apache.hop.ui.core.dialog.MessageBox.open(MessageBox.java:155)
        at org.apache.hop.imports.kettle.KettleImportDialog.doImport(KettleImportDialog.java:698)
        at org.apache.hop.imports.kettle.KettleImportDialog.lambda$open$0(KettleImportDialog.java:505)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:513)
        at org.apache.hop.imports.kettle.KettleImportDialog.open(KettleImportDialog.java:556)
        at org.apache.hop.imports.gui.HopImportGuiPlugin.menuToolsImport(HopImportGuiPlugin.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hop.ui.core.gui.GuiMenuWidgets.executeMenuItem(GuiMenuWidgets.java:174)
        at org.apache.hop.ui.hopgui.context.menu.MenuContextHandler.lambda$getSupportedActions$0(MenuContextHandler.java:103)
        at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5000)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4480)
        at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
`

### Issue Priority

Priority: 1

### Issue Component

Component: Import

**Comment by mattcasters** [comment]
Import works fine.  This is just an issue with the dialog that shows the overview of imported files.
