### ISSUE TITLE
[Bug]: Unable to open dialog for Filter rows transform

### ISSUE THREAD

**Issue by nadment** [apache/hop#2036]
### Apache Hop version?

2.2.0

### Java version?

11

### Operating system

Windows

### What happened?

Create Filter rows transform or open filter in integration-tests\database\run-all.hpl

java.lang.NoSuchMethodError: org.apache.hop.core.Condition.getLeftValueName()Ljava/lang/String;
	at org.apache.hop.ui.core.widget.ConditionEditor.drawAtomic(ConditionEditor.java:855)
	at org.apache.hop.ui.core.widget.ConditionEditor.repaint(ConditionEditor.java:749)
	at org.apache.hop.ui.core.widget.ConditionEditor.lambda$0(ConditionEditor.java:200)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1627)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4802)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5036)
	at org.eclipse.swt.internal.win32.OS.UpdateWindow(Native Method)
	at org.eclipse.swt.widgets.Decorations.setVisible(Decorations.java:1289)
	at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:2062)
	at org.eclipse.swt.widgets.Shell.open(Shell.java:1293)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:507)
	at org.apache.hop.pipeline.transforms.filterrows.FilterRowsDialog.open(FilterRowsDialog.java:213)

### Issue Priority

Priority: 1

### Issue Component

Component: Actions

**Comment by nadment** [comment]
Oups, it's my fault, not a bug
