### ISSUE TITLE
[Bug]: HIVE2 is not recognised in Apache Hop

### ISSUE THREAD

**Issue by pradoshsahoo2021** [apache/hop#2057]
### Apache Hop version?

2.2.0, 2.1.0

### Java version?

openjdk-11.0.2

### Operating system

Windows

### What happened?

Create a PDI job/transfomartion to connect Hive with Hive2 connection in kettle.
Try to import the job/transformation into Hop. It throws below error.
InvocationTargetException: Error importing org.apache.hop.core.exception.HopException: 
Error find files to import from PDI/Kettle into Hop project

Error importing database type 'HIVE2' from file 'file:///file1.ktr'
 at java.lang.Thread.run (Thread.java:834)
 at org.apache.hop.ui.core.dialog.ProgressMonitorDialog.lambda$run$2 (ProgressMonitorDialog.java:167)
 at org.apache.hop.imports.kettle.KettleImportDialog.lambda$doImport$4 (KettleImportDialog.java:686)
 at org.apache.hop.imp.HopImportBase.runImport (HopImportBase.java:112)
 at org.apache.hop.imports.kettle.KettleImport.findFilesToImport (KettleImport.java:117)
 at org.apache.hop.imports.kettle.KettleImport.handleHopFile (KettleImport.java:145)
 at org.apache.hop.imports.kettle.KettleImport.importDbConnections (KettleImport.java:378)
 at org.apache.hop.core.plugins.PluginRegistry.loadClass (PluginRegistry.java:293)

	at org.apache.hop.imports.kettle.KettleImport.findFilesToImport(KettleImport.java:134)
	at org.apache.hop.imp.HopImportBase.runImport(HopImportBase.java:112)
	at org.apache.hop.imports.kettle.KettleImportDialog.lambda$doImport$4(KettleImportDialog.java:686)
	at org.apache.hop.ui.core.dialog.ProgressMonitorDialog.lambda$run$2(ProgressMonitorDialog.java:167)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.hop.core.exception.HopException: 
Error importing database type 'HIVE2' from file 'file:///file1.ktr'
 at java.lang.Thread.run (Thread.java:834)
 at org.apache.hop.ui.core.dialog.ProgressMonitorDialog.lambda$run$2 (ProgressMonitorDialog.java:167)
 at org.apache.hop.imports.kettle.KettleImportDialog.lambda$doImport$4 (KettleImportDialog.java:686)
 at org.apache.hop.imp.HopImportBase.runImport (HopImportBase.java:112)
 at org.apache.hop.imports.kettle.KettleImport.findFilesToImport (KettleImport.java:117)
 at org.apache.hop.imports.kettle.KettleImport.handleHopFile (KettleImport.java:145)
 at org.apache.hop.imports.kettle.KettleImport.importDbConnections (KettleImport.java:378)
 at org.apache.hop.core.plugins.PluginRegistry.loadClass (PluginRegistry.java:293)

	at org.apache.hop.imports.kettle.KettleImport.importDbConnections(KettleImport.java:460)
	at org.apache.hop.imports.kettle.KettleImport.handleHopFile(KettleImport.java:145)
	at org.apache.hop.imports.kettle.KettleImport.findFilesToImport(KettleImport.java:117)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.apache.hop.core.plugins.PluginRegistry.loadClass(PluginRegistry.java:293)
	at org.apache.hop.imports.kettle.KettleImport.importDbConnections(KettleImport.java:378)
	... 6 more

### Issue Priority

Priority: 1

### Issue Component

Component: Plugins

**Comment by pradoshsahoo2021** [comment]
@hansva With Apache HOP 2.3 version, I am not able to connect to HIVE database. Is it possible to have a call to discuss this issue?

Error:
Error connecting to database [HIVE] :org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open client transport with JDBC Uri: jdbc:hive2://host:443/default?hive.exec.parallel=true&tez.am.resource.memory.mb=12288&transportMode=http&AuthMech=3&tez.queue.name=default&tez.grouping.max-size=16777216&mapreduce.input.fileinputformat.split.minsize=1048576&hive.fetch.task.conversion=none&AllowAllHostNames=1&UseNativeQuery=1&mapreduce.input.fileinputformat.split.maxsize=16777216&SSLKeyStorePwd=changeit&ssl=1&httpPath=gateway/cdp-proxy-api/hive&SSLKeyStore=abc.truststore&hive.tez.container.size=10480&tez.grouping.min-size=1048576&AllowSelfSignedCerts=1: Socket is closed by peer.


org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open client transport with JDBC Uri: jdbc:hive2://host:443/default?hive.exec.parallel=true&tez.am.resource.memory.mb=12288&transportMode=http&AuthMech=3&tez.queue.name=default&tez.grouping.max-size=16777216&mapreduce.input.fileinputformat.split.minsize=1048576&hive.fetch.task.conversion=none&AllowAllHostNames=1&UseNativeQuery=1&mapreduce.input.fileinputformat.split.maxsize=16777216&SSLKeyStorePwd=changeit&ssl=1&httpPath=gateway/cdp-proxy-api/hive&SSLKeyStore=abc.truststore&hive.tez.container.size=10480&tez.grouping.min-size=1048576&AllowSelfSignedCerts=1: Socket is closed by peer.


	at org.apache.hop.core.database.Database.normalConnect(Database.java:375)
	at org.apache.hop.core.database.Database.connect(Database.java:306)
	at org.apache.hop.core.database.DatabaseFactory.getConnectionTestReport(DatabaseFactory.java:47)
	at org.apache.hop.core.database.DatabaseFactory.getConnectionTestResults(DatabaseFactory.java:72)
	at org.apache.hop.core.database.DatabaseMeta.testConnectionSuccess(DatabaseMeta.java:2053)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.testConnection(DatabaseMetaEditor.java:857)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.test(DatabaseMetaEditor.java:744)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.lambda$createButtonsForButtonBar$6(DatabaseMetaEditor.java:912)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
Caused by: org.apache.hop.core.exception.HopDatabaseException: 
Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open client transport with JDBC Uri: jdbc:hive2://host:443/default?hive.exec.parallel=true&tez.am.resource.memory.mb=12288&transportMode=http&AuthMech=3&tez.queue.name=default&tez.grouping.max-size=16777216&mapreduce.input.fileinputformat.split.minsize=1048576&hive.fetch.task.conversion=none&AllowAllHostNames=1&UseNativeQuery=1&mapreduce.input.fileinputformat.split.maxsize=16777216&SSLKeyStorePwd=changeit&ssl=1&httpPath=gateway/cdp-proxy-api/hive&SSLKeyStore=abc.truststore&hive.tez.container.size=10480&tez.grouping.min-size=1048576&AllowSelfSignedCerts=1: Socket is closed by peer.

	at org.apache.hop.core.database.Database.connectUsingClass(Database.java:470)
	at org.apache.hop.core.database.Database.normalConnect(Database.java:360)
	... 14 more
Caused by: java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://host:443/default?hive.exec.parallel=true&tez.am.resource.memory.mb=12288&transportMode=http&AuthMech=3&tez.queue.name=default&tez.grouping.max-size=16777216&mapreduce.input.fileinputformat.split.minsize=1048576&hive.fetch.task.conversion=none&AllowAllHostNames=1&UseNativeQuery=1&mapreduce.input.fileinputformat.split.maxsize=16777216&SSLKeyStorePwd=changeit&ssl=1&httpPath=gateway/cdp-proxy-api/hive&SSLKeyStore=abc.truststore&hive.tez.container.size=10480&tez.grouping.min-size=1048576&AllowSelfSignedCerts=1: Socket is closed by peer.
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:256)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
	at org.apache.hop.core.database.DelegatingDriver.connect(DelegatingDriver.java:45)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.hop.core.database.Database.connectUsingClass(Database.java:454)
	... 15 more
Caused by: org.apache.thrift.transport.TTransportException: Socket is closed by peer.
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:184)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:109)
	at org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:151)
	at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:272)
	at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:39)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:343)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:228)
	... 20 more

Hostname:	host
Port:	443
Database name:	default
Url:	jdbc:hive2://host:443/default?hive.exec.parallel=true&tez.am.resource.memory.mb=12288&transportMode=http&AuthMech=3&tez.queue.name=default&tez.grouping.max-size=16777216&mapreduce.input.fileinputformat.split.minsize=1048576&hive.fetch.task.conversion=none&AllowAllHostNames=1&UseNativeQuery=1&mapreduce.input.fileinputformat.split.maxsize=16777216&SSLKeyStorePwd=changeit&ssl=1&httpPath=gateway/cdp-proxy-api/hive&SSLKeyStore=abc.truststore&hive.tez.container.size=10480&tez.grouping.min-size=1048576&AllowSelfSignedCerts=1

**Comment by bamaer** [comment]
what are your connection settings? Do you use the Apache Hive database type? 
can you connect to your Hive database with similar Java-base tools e.g. DBeaver? 

we have a (working) [integration test](https://ci-builds.apache.org/job/Hop/job/Hop-integration-tests/lastCompletedBuild/testReport/(root)/spark/) for Apache Hive.  It could be worth checking if your configuration is similar.

**Comment by pradoshsahoo2021** [comment]
I am able to connect Hive from DBeaver and PDI. Both works with HiveJDBC41/42 jar. Is it included in your Hive library?

**Comment by hansva** [comment]
you can check what is included under plugins/database/hive/lib but we include the JDBC driver needed to connect.
We are using Hive on Spark 3.3 for our testing

**Comment by bamaer** [comment]
the Hive database plugin ships with the following libraries in `plugins/databases/hive/lib`:

* hadoop-client-3.3.4.jar
* hive-common-3.1.3.jar
* hive-jdbc-3.1.3.jar
* hive-metastore-3.1.3.jar
* hive-serde-3.1.3.jar
* hive-service-3.1.3.jar
* hive-service-rpc-3.1.3.jar
* libthrift-0.16.0.jar

**Comment by pradoshsahoo2021** [comment]
We are using below drivers to connect to Hive from PDI and DBeaver.

![image](https://user-images.githubusercontent.com/120457193/218450633-4aea4708-a9d1-40e4-9dbb-d2a5767cfe6a.png)

**Comment by bamaer** [comment]
* lib/core/commons-codec-1.15.jar
* lib/core/commons-logging-1.1.3.jar
* plugins/databases/hive/lib/hive-metastore-3.1.3.jar
* plugins/databases/hive/lib/hive-service-3.1.3.jar
* plugins/databases/hive/lib/hive-jdbc-3.1.3.jar
* lib/core/httpclient-4.5.13.jar and lib/core/commons-httpclient-3.1.jar
* lib/core/httpcore-4.4.15.jar
* libfb: not shipped with Apache Hop 
* plugins/databases/hive/lib/libthrift-0.16.0.jar
* ql: not shipped with Apache Hop 
* lib/beam/slf4j-api-2.0.4.jar
* TCLIServiceClient: not shipped with Apache Hop 
* zookeeper: shipped with the Apache Beam and Apache Parquet plugins, not part of core or the Apache Hive plugin. 

I'm not sure what `ql.jar` is, can you try adding that jar and TCLIServiceClient.jar to your `plugins/databases/hive/lib` and check if that makes a difference?

**Comment by pradoshsahoo2021** [comment]
With ql.jar and TLIServiceClient.jar, I am getting same error.

**Comment by bamaer** [comment]
we'll need to find a reproduction path. 
can you share your Hive version? is there any special configuration on the hive side or a configuration that you added in PDI and/or DBeaver?

**Comment by pradoshsahoo2021** [comment]
In PDI and DBeaver I am using below drivers and parameters.
Drivers:
![image](https://user-images.githubusercontent.com/120457193/218669333-dacb8631-6863-4d0e-8d82-1fb5796b6340.png)

Parameters:
![image](https://user-images.githubusercontent.com/120457193/218669715-9d63670b-2164-4477-943b-1c5b354a8b2b.png)


Below class is used in DBeaver driver setting:
com.cloudera.hive.jdbc.HS2Driver

**Comment by hansva** [comment]
What type of system is this? custom Hadoop stack? cloudera? which version(s)? 
We need something to test/reproduce the issue against

**Comment by pradoshsahoo2021** [comment]
We are using Cloudera CDP 7.1.7. 
Our hive version is 3.1.3.

**Comment by mattcasters** [comment]
Apache Hop supports standard Hive servers through class `org.apache.hive.jdbc.HiveDriver`.

**Comment by pradoshsahoo2021** [comment]
Hi @mattcasters ,

We are using PDI 6 for all our ETL pipelines. We are planning to migrate to Apache HOP and We found this is a blocking issue for us as HOP cannot connect to our Hive server whereas PDI works fine with our Hive. In PDI Hadoop HIVE and Hadoop HIVE2 connection types are available. Whereas in HOP only Apache HIVE is available. we use HIVE2 database connection type in our case. While using HOP we found below issues.
1. Apache HOP is not able to connect to our HIVE server.
2. All the jobs using HIVE2 connection type cannot be imported as HOP doesn't know about HIVE2.

Could you please suggest if there is any possible solutions for this?

**Comment by mattcasters** [comment]
@pradoshsahoo2021 I do hope you understand that Apache Hop as a project and ASF as an organization is not responsible for providing solutions for your specific issue.  

Apache Hop can only ship with JDBC drivers that are compatible with an Apache license.  In this specific scenario I suggest you try to connect with the Cloudera Hive JDBC driver: https://www.cloudera.com/downloads/connectors/hive/jdbc/2-6-5.html

Perhaps you can use the Generic connection type to try this.  If you are successful we can consider adding a "Cloudera Hive" database type to Apache Hop without the driver itself.

Thanks in advance for helping out the project.  Remember that we are in no way shape or form involved with or responsible for past or present PDI versions.

**Comment by pradoshsahoo2021** [comment]
Hi @mattcasters , I am able to connect to Hive with above driver using generic connection. Thanks for your help. :)
