### ISSUE TITLE
[Bug]: Remote Execution information location failing to display data for pipeline

### ISSUE THREAD

**Issue by selvasuriya** [apache/hop#2104]
### Apache Hop version?

2.2.0

### Java version?

17

### Operating system

Windows

### What happened?

Created sample pipeline:
![image](https://user-images.githubusercontent.com/120563966/209545450-9f82a0e4-bc6b-4379-8956-d5986223d0ed.png)

Hop server setup in hop gui:
![image](https://user-images.githubusercontent.com/120563966/209545508-6c4b7c8c-99ae-4636-8e61-9387cbab2db6.png)

Remote Execution Information location:
![image](https://user-images.githubusercontent.com/120563966/209545564-3bcb9609-59e8-4ab4-8e1a-11c52412c66f.png)

Hop server status:
![image](https://user-images.githubusercontent.com/120563966/209545654-792c067a-0c4e-4e1a-a24b-7ded5fc5b50e.png)

Remote execution info location :
![image](https://user-images.githubusercontent.com/120563966/209545744-70c1e59f-f13d-43be-8d6a-6108bb615ea2.png)

When click on data grid transform we get below error:
![image](https://user-images.githubusercontent.com/120563966/209545853-9fc2647e-f359-4543-8db2-42750f353089.png)

Error 

HopException: 
Error getting execution data from remote location
Cannot construct instance of `org.apache.hop.execution.ExecutionData` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('org.apache.hop.core.exception.HopException: 
Please specify the execution ID with parameter 'id'

	at org.apache.hop.www.GetExecutionInfoServlet.doGet(GetExecutionInfoServlet.java:202)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.apache.hop.www.BaseHttpServlet.service(BaseHttpServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:567)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)')
 at [Source: (String)""org.apache.hop.core.exception.HopException: \r\nPlease specify the execution ID with parameter 'id'\r\n\r\n\tat org.apache.hop.www.GetExecutionInfoServlet.doGet(GetExecutionInfoServlet.java:202)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\r\n\tat org.apache.hop.www.BaseHttpServlet.service(BaseHttpServlet.java:103)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\r\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)\r\n\tat or"[truncated 2690 chars]; line: 1, column: 1]

Root cause: MismatchedInputException: Cannot construct instance of `org.apache.hop.execution.ExecutionData` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('org.apache.hop.core.exception.HopException: 
Please specify the execution ID with parameter 'id'

	at org.apache.hop.www.GetExecutionInfoServlet.doGet(GetExecutionInfoServlet.java:202)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.apache.hop.www.BaseHttpServlet.service(BaseHttpServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:567)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)')
 at [Source: (String)""org.apache.hop.core.exception.HopException: \r\nPlease specify the execution ID with parameter 'id'\r\n\r\n\tat org.apache.hop.www.GetExecutionInfoServlet.doGet(GetExecutionInfoServlet.java:202)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)\r\n\tat org.apache.hop.www.BaseHttpServlet.service(BaseHttpServlet.java:103)\r\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\r\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)\r\n\tat or"[truncated 2690 chars]; line: 1, column: 1]

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
should have been resolved along the way
