### ISSUE TITLE
[Bug]: Apache HoP is not able to connect to Apache Hive

### ISSUE THREAD

**Issue by pradoshsahoo2021** [apache/hop#2143]
### Apache Hop version?

2.2.0, 2.1.0

### Java version?

openjdk-11.0.2

### Operating system

Windows

### What happened?

Create a database connection to Apache Hive.
Test the connection. It throws below error.
Error connecting to database [39_UDEX_HIVE] :org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open connection to jdbc:hive2:<JDBC URL>

org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open connection to jdbc:hive2:<JDBC URL>

	at org.apache.hop.core.database.Database.normalConnect(Database.java:375)
	at org.apache.hop.core.database.Database.connect(Database.java:306)
	at org.apache.hop.core.database.DatabaseFactory.getConnectionTestReport(DatabaseFactory.java:47)
	at org.apache.hop.core.database.DatabaseFactory.getConnectionTestResults(DatabaseFactory.java:72)
	at org.apache.hop.core.database.DatabaseMeta.testConnectionSuccess(DatabaseMeta.java:2053)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.testConnection(DatabaseMetaEditor.java:857)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.test(DatabaseMetaEditor.java:744)
	at org.apache.hop.ui.core.database.DatabaseMetaEditor.lambda$createButtonsForButtonBar$6(DatabaseMetaEditor.java:912)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
Caused by: org.apache.hop.core.exception.HopDatabaseException: 
Error connecting to database: (using class org.apache.hive.jdbc.HiveDriver)
Could not open connection to jdbc:hive2:<JDBC URL>

	at org.apache.hop.core.database.Database.connectUsingClass(Database.java:470)
	at org.apache.hop.core.database.Database.normalConnect(Database.java:360)
	... 14 more
Caused by: java.sql.SQLException: Could not open connection to jdbc:hive2:<JDBC URL>
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:206)
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:178)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at org.apache.hop.core.database.DelegatingDriver.connect(DelegatingDriver.java:45)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at org.apache.hop.core.database.Database.connectUsingClass(Database.java:454)
	... 15 more
Caused by: io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TTransportException
	at io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132)
	at io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TSaslTransport.receiveSaslMessage(TSaslTransport.java:178)
	at io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:305)
	at io.trino.hive.jdbc.$internal.org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:38)
	at org.apache.hive.jdbc.HiveConnection.openTransport(HiveConnection.java:203)
	... 21 more

Hostname:	<hostname>
Port: <port>
Database name:	default
Url:	jdbc:hive2:<JDBC URL>

### Issue Priority

Priority: 1

### Issue Component

Component: Database

**Comment by hansva** [comment]
can you connect to your Hive database using another JDBC tool such as DBeaver?
Have you redacted the hostname and port and was it actually filled in when trying to connect?

**Comment by pradoshsahoo2021** [comment]
> can you connect to your Hive database using another JDBC tool such as DBeaver? Have you redacted the hostname and port and was it actually filled in when trying to connect?

I am able to connect to Hive from DBeaver and kettle. I also compared the JDBC connection string form Kettle and HOP, both are identical. Still I am getting error when connecting to Hive from Apache Hop.
Note: I am using the same libraries in both Kettle and Hop.

**Comment by pradoshsahoo2021** [comment]
First I got below error with the existing drivers. After that I replaced them with drivers I am using in kettle and Dbeaver. 

Error in the Hop GUI : org/apache/hadoop/shaded/com/ctc/wstx/io/InputBootstrapper

java.lang.NoClassDefFoundError: org/apache/hadoop/shaded/com/ctc/wstx/io/InputBootstrapper

        at org.apache.hadoop.fs.FileSystem.<clinit>(FileSystem.java:206)

        at org.apache.hadoop.hive.conf.valcoersion.JavaIOTmpdirVariableCoercion.<clinit>(JavaIOTmpdirVariableCoercion.java:37)

        at org.apache.hadoop.hive.conf.SystemVariables.<clinit>(SystemVariables.java:37)

        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<init>(HiveConf.java:5772)

        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<init>(HiveConf.java:5753)

        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:493)

        at org.apache.hive.jdbc.Utils$JdbcConnectionParams.<clinit>(Utils.java:205)

        at org.apache.hive.jdbc.Utils.extractURLComponents(Utils.java:431)

        at org.apache.hive.jdbc.Utils.parseURL(Utils.java:412)

        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:294)

        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:282)

        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:94)

        at org.apache.hop.core.database.DelegatingDriver.connect(DelegatingDriver.java:45)

        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)

        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)

        at org.apache.hop.core.database.Database.connectUsingClass(Database.java:454)

        at org.apache.hop.core.database.Database.normalConnect(Database.java:360)

        at org.apache.hop.core.database.Database.connect(Database.java:306)

        at org.apache.hop.core.database.DatabaseFactory.getConnectionTestReport(DatabaseFactory.java:47)

        at org.apache.hop.core.database.DatabaseFactory.getConnectionTestResults(DatabaseFactory.java:72)

        at org.apache.hop.core.database.DatabaseMeta.testConnectionSuccess(DatabaseMeta.java:2053)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.testConnection(DatabaseMetaEditor.java:857)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.test(DatabaseMetaEditor.java:744)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.lambda$createButtonsForButtonBar$6(DatabaseMetaEditor.java:912)

        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)

        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)

        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)

        at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)

        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

Caused by: java.lang.ClassNotFoundException: Unable to load class 'org.apache.hadoop.shaded.com.ctc.wstx.io.InputBootstrapper' in this classloader or in the parent

        at org.apache.hop.core.plugins.HopURLClassLoader.loadClass(HopURLClassLoader.java:96)

        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

        ... 31 more

Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.shaded.com.ctc.wstx.io.InputBootstrapper

        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)

        at org.apache.hop.core.plugins.HopURLClassLoader.loadClassFromThisLoader(HopURLClassLoader.java:66)

        at org.apache.hop.core.plugins.HopURLClassLoader.loadClass(HopURLClassLoader.java:91)

        ... 32 more

 

Error in the Hop GUI : Could not initialize class org.apache.hive.jdbc.Utils$JdbcConnectionParams

java.lang.NoClassDefFoundError: Could not initialize class org.apache.hive.jdbc.Utils$JdbcConnectionParams

        at org.apache.hive.jdbc.Utils.extractURLComponents(Utils.java:431)

        at org.apache.hive.jdbc.Utils.parseURL(Utils.java:412)

        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:294)

        at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:282)

        at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:94)

        at org.apache.hop.core.database.DelegatingDriver.connect(DelegatingDriver.java:45)

        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)

        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)

        at org.apache.hop.core.database.Database.connectUsingClass(Database.java:454)

        at org.apache.hop.core.database.Database.normalConnect(Database.java:360)

        at org.apache.hop.core.database.Database.connect(Database.java:306)

        at org.apache.hop.core.database.DatabaseFactory.getConnectionTestReport(DatabaseFactory.java:47)

        at org.apache.hop.core.database.DatabaseFactory.getConnectionTestResults(DatabaseFactory.java:72)

        at org.apache.hop.core.database.DatabaseMeta.testConnectionSuccess(DatabaseMeta.java:2053)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.testConnection(DatabaseMetaEditor.java:857)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.test(DatabaseMetaEditor.java:744)

        at org.apache.hop.ui.core.database.DatabaseMetaEditor.lambda$createButtonsForButtonBar$6(DatabaseMetaEditor.java:912)

        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)

        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)

        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)

        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)

        at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)

        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

**Comment by hansva** [comment]
thanks for the extra info, will look into it.

**Comment by hansva** [comment]
.take-issue
