### ISSUE TITLE
[Bug]: String Operations - SWT Widget Disposed 

### ISSUE THREAD

**Issue by hansva** [apache/hop#2268]
### Apache Hop version?

2.2

### Java version?

11

### Operating system

Windows

### What happened?

Import: https://issues.apache.org/jira/browse/HOP-4609

Working in the step going from "Upper/Lower" "Y" to "InitCap "Y" for each row and somewhere along the work this SWT box few up.

```
org.eclipse.swt.SWTException: Widget is disposed
        at org.eclipse.swt.SWT.error(SWT.java:4918)
        at org.eclipse.swt.SWT.error(SWT.java:4833)
        at org.eclipse.swt.SWT.error(SWT.java:4804)
        at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:480)
        at org.eclipse.swt.widgets.Combo.getText(Combo.java:1354)
        at org.apache.hop.ui.core.widget.TableView.applyComboChange(TableView.java:1767)
        at org.apache.hop.ui.core.widget.TableView$2.mouseDown(TableView.java:577)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:500)
        at org.apache.hop.pipeline.transforms.stringoperations.StringOperationsDialog.open(StringOperationsDialog.java:275)
        at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3341)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseDoubleClick(HopGuiPipelineGraph.java:596)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:200)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
```

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Cannot reproduce
