### ISSUE TITLE
[Bug]: Postgres Bulk Loader - NPE when pressing SQL button.

### ISSUE THREAD

**Issue by hansva** [apache/hop#2272]
### Apache Hop version?

2.2

### Java version?

11

### Operating system

Windows

### What happened?

Import: https://issues.apache.org/jira/browse/HOP-4599
I was trying to go from a table input to the Postgres Bulk loader.  The table did not exist, but the schema and database do.  When I hit the "SQL" button to get a suggestion for how to create the destination table, I got an NPE saying "Unable to open dialog for this transformation"
![image](https://user-images.githubusercontent.com/1140235/217817479-a33203ec-0221-4a33-91ac-636ee91d2a73.png)
```
2022/11/16 15:38:02 - Preview pipeline for Table input - Execution finished on a local pipeline engine with run configuration 'local'
java.lang.NullPointerException
        at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoaderDialog.getInfo(PGBulkLoaderDialog.java:691)
        at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoaderDialog.create(PGBulkLoaderDialog.java:817)
        at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoaderDialog.lambda$open$5(PGBulkLoaderDialog.java:429)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:500)
        at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoaderDialog.open(PGBulkLoaderDialog.java:444)
        at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3341)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseDoubleClick(HopGuiPipelineGraph.java:596)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:200)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
        at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:500)
        at org.apache.hop.pipeline.transforms.tableinput.TableInputDialog.open(TableInputDialog.java:341)
        at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3341)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2162)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
        at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5000)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4480)
        at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
```

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
.take-issue
