### ISSUE TITLE
[Bug]: Error deleting last entry Execution Information

### ISSUE THREAD

**Issue by hansva** [apache/hop#2290]
### Apache Hop version?

2.2

### Java version?

11

### Operating system

Windows

### What happened?

Import: https://issues.apache.org/jira/browse/HOP-4545
org.apache.hop.core.exception.HopException: 
Error deleting execution with ID f832eb71-5c6a-4335-992f-8c1021ef62a9
Error deleting execution with ID 9a471877-0976-42b2-a4a8-375760984ad3
Error deleting execution with ID 1ebb8dcc-6bd3-4290-885a-0fb50b28ee9d
Error deleting execution with ID 5c4b67c5-dbc9-48de-85e5-5aff295cc410
Error deleting execution with ID 28145220-308d-44ef-b181-27bb1ed56a49
Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926
Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!
![image](https://user-images.githubusercontent.com/1140235/217837741-9bc227ad-2eaf-4013-bed1-59794f80da05.png)

```

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.ui.hopgui.perspective.execution.ExecutionPerspective.delete(ExecutionPerspective.java:694)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:188)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5796)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
    at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:447)
    at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:336)
Caused by: org.apache.hop.core.exception.HopException: 
Error deleting execution with ID 9a471877-0976-42b2-a4a8-375760984ad3

Error deleting execution with ID 1ebb8dcc-6bd3-4290-885a-0fb50b28ee9d

Error deleting execution with ID 5c4b67c5-dbc9-48de-85e5-5aff295cc410

Error deleting execution with ID 28145220-308d-44ef-b181-27bb1ed56a49

Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

 

 

 

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:137)
    ... 13 more
Caused by: org.apache.hop.core.exception.HopException: 
Error deleting execution with ID 1ebb8dcc-6bd3-4290-885a-0fb50b28ee9d

Error deleting execution with ID 5c4b67c5-dbc9-48de-85e5-5aff295cc410

Error deleting execution with ID 28145220-308d-44ef-b181-27bb1ed56a49

Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

 

 

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:137)
    ... 14 more
Caused by: org.apache.hop.core.exception.HopException: 
Error deleting execution with ID 5c4b67c5-dbc9-48de-85e5-5aff295cc410

Error deleting execution with ID 28145220-308d-44ef-b181-27bb1ed56a49

Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

 

 

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:137)
    ... 15 more
Caused by: org.apache.hop.core.exception.HopException: 
Error deleting execution with ID 28145220-308d-44ef-b181-27bb1ed56a49

Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

 

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:137)
    ... 16 more
Caused by: org.apache.hop.core.exception.HopException: 
Error deleting execution with ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

 

    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:150)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:137)
    ... 17 more
Caused by: org.apache.hop.core.exception.HopException: 
Error finding child executions for parent ID 897e9e02-70c7-43b5-a69c-69b07459e926

Error listing execution IDs
Comparison method violates its general contract!

    at org.apache.hop.execution.local.FileExecutionInfoLocation.findExecutions(FileExecutionInfoLocation.java:389)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.deleteExecution(FileExecutionInfoLocation.java:135)
    ... 18 more
Caused by: org.apache.hop.core.exception.HopException: 
Error listing execution IDs
Comparison method violates its general contract!

    at org.apache.hop.execution.local.FileExecutionInfoLocation.getExecutionIds(FileExecutionInfoLocation.java:312)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.findExecutions(FileExecutionInfoLocation.java:381)
    ... 19 more
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
    at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
    at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
    at java.base/java.util.TimSort.sort(TimSort.java:254)
    at java.base/java.util.Arrays.sort(Arrays.java:1515)
    at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
    at java.base/java.util.Collections.sort(Collections.java:179)
    at org.apache.hop.execution.local.FileExecutionInfoLocation.getExecutionIds(FileExecutionInfoLocation.java:299)
    ... 20 more
```

### Issue Priority

Priority: 2

### Issue Component

Component: Other

**Comment by mattcasters** [comment]
This was fixed.
