### ISSUE TITLE
[Task]: Update GoogleDrive VFS

### ISSUE THREAD

**Issue by hansva** [apache/hop#2524]
### What needs to happen?

The GoogleDrive VFS uses old style key and some of the underlying libraries are outdated.
Also make it possible to use the instance role to use authentication.

### Issue Priority

Priority: 2

### Issue Component

Component: VFS

**Comment by MoisesArruda** [comment]
Same problem here

**Comment by pauloricardoferreira** [comment]
Same problem here.

Config:

![image](https://user-images.githubusercontent.com/70301866/224782384-aa6db4c1-e9b6-40a8-9ec7-2313f7902980.png)

Json:

![image](https://user-images.githubusercontent.com/70301866/224782562-2295fcdb-88a9-4d98-9502-c749e319e04b.png)

Logs Text Input:

Error browsing to location: 'googledrive://'
HopFileException: 

Unable to get VFS File object for filename 'googledrive://' : Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".
Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".

Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".

Root cause: IllegalArgumentException: 

org.apache.hop.core.exception.HopFileException: 

Unable to get VFS File object for filename 'googledrive://' : Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".
Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".

Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".

	at org.apache.hop.core.vfs.HopVfs.getFileObject(HopVfs.java:194)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.refreshBrowser(HopVfsFileDialog.java:878)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.enteredFilenameOrFolder(HopVfsFileDialog.java:684)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.lambda$open$2(HopVfsFileDialog.java:329)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.open(HopVfsFileDialog.java:581)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:263)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:163)
	at org.apache.hop.pipeline.transforms.fileinput.text.TextFileInputDialog.lambda$open$8(TextFileInputDialog.java:470)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:513)
	at org.apache.hop.pipeline.transforms.fileinput.text.TextFileInputDialog.open(TextFileInputDialog.java:487)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3342)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
Caused by: org.apache.commons.vfs2.FileSystemException: Unknown message with code "Unable to get Google Drive file object for 'googledrive:///'".
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.processFile(GoogleDriveFileSystem.java:75)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.resolveFile(GoogleDriveFileSystem.java:54)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:75)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:55)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:788)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:754)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:819)
	at org.apache.hop.core.vfs.HopVfs.getFileObject(HopVfs.java:188)
	... 34 more
Caused by: org.apache.commons.vfs2.FileSystemException
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.<init>(GoogleDriveFileObject.java:99)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.createFile(GoogleDriveFileSystem.java:40)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.processFile(GoogleDriveFileSystem.java:73)
	... 41 more
Caused by: java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:131)
	at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:35)
	at com.google.api.client.googleapis.auth.oauth2.GoogleClientSecrets.getDetails(GoogleClientSecrets.java:80)
	at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeFlow$Builder.<init>(GoogleAuthorizationCodeFlow.java:211)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.getCredentials(GoogleDriveFileObject.java:245)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.getDriveService(GoogleDriveFileObject.java:255)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.<init>(GoogleDriveFileObject.java:96)
	... 43 more

**Comment by pauloricardoferreira** [comment]
Ow.. new error.


the consent screen appeared to give permission and then it displayed the error below

Error browsing to location: 'googledrive://'
ExceptionInInitializerError: 
Root cause: IllegalStateException: You are currently running with version 2.0.1 of google-api-client. You need at least version 1.15 of google-api-client to run version 1.25.0 of the Drive API library.

java.lang.ExceptionInInitializerError
	at com.google.api.services.drive.Drive$Builder.build(Drive.java:10116)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.getDriveService(GoogleDriveFileObject.java:258)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileObject.<init>(GoogleDriveFileObject.java:96)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.createFile(GoogleDriveFileSystem.java:40)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.processFile(GoogleDriveFileSystem.java:73)
	at org.apache.hop.vfs.googledrive.GoogleDriveFileSystem.resolveFile(GoogleDriveFileSystem.java:54)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:75)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:55)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:788)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:754)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:819)
	at org.apache.hop.core.vfs.HopVfs.getFileObject(HopVfs.java:188)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.refreshBrowser(HopVfsFileDialog.java:878)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.enteredFilenameOrFolder(HopVfsFileDialog.java:684)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.lambda$open$2(HopVfsFileDialog.java:329)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.open(HopVfsFileDialog.java:581)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:263)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:163)
	at org.apache.hop.pipeline.transforms.fileinput.text.TextFileInputDialog.lambda$open$8(TextFileInputDialog.java:470)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:513)
	at org.apache.hop.pipeline.transforms.fileinput.text.TextFileInputDialog.open(TextFileInputDialog.java:487)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3342)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:464)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
Caused by: java.lang.IllegalStateException: You are currently running with version 2.0.1 of google-api-client. You need at least version 1.15 of google-api-client to run version 1.25.0 of the Drive API library.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:534)
	at com.google.api.client.util.Preconditions.checkState(Preconditions.java:113)
	at com.google.api.services.drive.Drive.<clinit>(Drive.java:48)
	... 46 more

**Comment by hansva** [comment]
We can tackle it all with this ticket and add some tests to check if everything keeps working.
The documentation could probably also use an update when we start working on this

**Comment by pauloricardoferreira** [comment]
Hello...

They managed to move forward with this Ticket.

I'm on version 2.9.0 and the problem still persists.

**Comment by pauloricardoferreira** [comment]
I found another problem with Google VFS.

When trying to access the folder where the Google credentials are, I am receiving the error below.


![image](https://github.com/user-attachments/assets/3499642b-40ee-483a-99e4-949729eebdc8)



Error browsing to location: 'C:\opt\apache\hop\google'
ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
Root cause: ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.populateFolder(HopVfsFileDialog.java:1003)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.refreshBrowser(HopVfsFileDialog.java:897)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.fileDefaultSelected(HopVfsFileDialog.java:812)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.apache.hop.ui.core.vfs.HopVfsFileDialog.open(HopVfsFileDialog.java:581)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:269)
	at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:163)
	at org.apache.hop.ui.core.gui.GuiCompositeWidgets.lambda$getTextControl$2(GuiCompositeWidgets.java:488)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

**Comment by gingras** [comment]
Still getting "Unable to get VFS File object for filename 'googledrive://'" and "Index -1 out of bounds for length 0" on version 2.10.  No replies in a while, has anyone gotten this working?

**Comment by dave-csc** [comment]
Same occurs in the new version 2.11.0.

As a workaround, you can use [the command-line utility to set the credentials](https://hop.apache.org/manual/latest/vfs/google-drive-vfs.html)

> I found another problem with Google VFS.
> 
> When trying to access the folder where the Google credentials are, I am receiving the error below.
> 
> ![image](https://private-user-images.githubusercontent.com/70301866/350382952-3499642b-40ee-483a-99e4-949729eebdc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwOTA3MzIsIm5iZiI6MTczNDA5MDQzMiwicGF0aCI6Ii83MDMwMTg2Ni8zNTAzODI5NTItMzQ5OTY0MmItNDBlZS00ODNhLTk5ZTQtOTQ5NzI5ZWViZGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDExNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYjNlODVlMTUyMGNmZjZjMTM2NTZhYjMyY2YwYmVjMmQyYWRmMDQ4MTQ2MjA4M2M5YzI4YjA3NDcyNTUxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MC3x6sJUzMbdabDvwyZ8q7vOaUpYybHGTyfi6pnKavU)
> 
> Error browsing to location: 'C:\opt\apache\hop\google' ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0 Root cause: ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
> 
> java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0 at org.apache.hop.ui.core.vfs.HopVfsFileDialog.populateFolder(HopVfsFileDialog.java:1003) at org.apache.hop.ui.core.vfs.HopVfsFileDialog.refreshBrowser(HopVfsFileDialog.java:897) at org.apache.hop.ui.core.vfs.HopVfsFileDialog.fileDefaultSelected(HopVfsFileDialog.java:812) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066) at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642) at org.apache.hop.ui.core.vfs.HopVfsFileDialog.open(HopVfsFileDialog.java:581) at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:269) at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:163) at org.apache.hop.ui.core.gui.GuiCompositeWidgets.lambda$getTextControl$2(GuiCompositeWidgets.java:488) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066) at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642) at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473) at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

**Comment by hansva** [comment]
In the message, it will tell you the path to go to the URL to activate the key.
I could not figure out how to open the browser the documentation is all over the place

**Comment by dave-csc** [comment]
Hi @hansva,

the problem is that you can't select the credentials file from Hop GUI, and you need to do this using the command line.

It's not an authentication problem: once this file and the token folder are specified, when you try to access your Google Drive you get the activation URL in the console as you stated...
