### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hansva** [apache/hop#2737]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-3573

You get an error when you want to sort a column in the preview and the data has a JSON ValueMeta. This happens even when sorting another column.

![image](https://user-images.githubusercontent.com/1140235/226371810-a281091d-d817-4b3e-a9c7-ed77d33723ef.png)

```
org.apache.hop.core.exception.HopValueException: 
FIELD_JSON String : I can't convert the specified value to data type : 11

    at org.apache.hop.core.row.value.ValueMetaBase.convertDataUsingConversionMetaData(ValueMetaBase.java:4044)
    at org.apache.hop.ui.core.widget.TableView.sortTable(TableView.java:1477)
    at org.apache.hop.ui.core.widget.TableView.sortTable(TableView.java:1370)
    at org.apache.hop.ui.core.widget.TableView.lambda$new$3(TableView.java:1206)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
    at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:480)
    at org.apache.hop.ui.core.dialog.PreviewRowsDialog.open(PreviewRowsDialog.java:249)
    at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.showTransformOutputData(HopGuiPipelineGraph.java:1169)
    at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.showTransformOutputData(HopGuiPipelineGraph.java:1099)
    at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseUp(HopGuiPipelineGraph.java:844)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
    at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:379)
    at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:299)
```

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
To solve the issue below simply, I want to integrate ValueMetaJson into the Core library. It's not an ideal solution, but I can't see any other way of dealing with it at the moment. However, we'll have the same problem again if a plugin adds a new IValueMeta type.

ValueMetaAvroRecord is also in the Core.

**Comment by hansva** [comment]
I think data types should just be part of core

**Comment by hansva** [comment]
this should be fixed
