### ISSUE TITLE
[Bug]: HOP WEB UI Server Error Application Terminated Unexpectedly

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#2801]
### Apache Hop version?

2.4.0

### Java version?

11.0.14

### Operating system

Docker

### What happened?

While using HOP web (HOP 2.4) when we try to update the steps i.e in the table input step, update the SQL query and try to save the changes we are frequently facing the "server error application terminated unexpectedly" issue.

Installation details: 
- Docker install on Ubuntu.
- Install: Pull the latest build with: docker pull apache/hop-web Via docker.compose.yml
{
version: '3.7'
services:
  hop-server:
    image: apache/hop:latest
    ports:
     - "8080:8080"
    volumes:
      - hop-server-data:/home/hop/data
    environment:
      - HOP_LOG_LEVEL=BASIC
    restart: always
  hop-web:
    image: apache/hop-web:latest
    ports:
      - "8088:8080"
    volumes:
      - hop-web-data:/home/hop/.hop
    environment:
      - HOP_SERVER_HOSTNAME=hop-server
      - HOP_SERVER_PORT=8080
      - HOP_LOG_LEVEL=BASIC
    restart: always
volumes:
  hop-server-data:
  hop-web-data:
}
- Run: Start Hop Web with $ docker-compose up --build

Reproduction Steps:-
1. Open HOP Web 2.4 via Chrome
2. Open Table input step in a existing Pipeline. 
3. Modify the existing query in the table input step.
4. Save the pipeline.

We get the "server error application terminated unexpectedly" issue.

Please refer the log file for more detailed logs.

[localhost.2023-04-03.log](https://github.com/apache/hop/files/11135955/localhost.2023-04-03.log)
[localhost_access_log.2023-04-03.txt](https://github.com/apache/hop/files/11135956/localhost_access_log.2023-04-03.txt)
![HOP Server Error](https://user-images.githubusercontent.com/31061958/229519855-c6502a7b-4fec-4b98-89fe-4b995d865bae.jpg)

However, on the HOP GUI tool it works fine without error.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Web

**Comment by bamaer** [comment]
I just tried to reproduce with the steps you describe, but this seems to work correctly. 

You mention changing the query in a table input transform triggers the error, but your screenshot shows the metadata perspective, and the stacktraces in the `localhost.2023-04-03.log` file you added point to (a keystroke event in) the explorer perspective.

The error is there, we'll just need to work out a clear reproduction path. Can you please provide some more details on how/when you get this error?

```
03-Apr-2023 07:28:04.574 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [HopGui] in context with path [] threw exception
	org.eclipse.swt.SWTException: Widget is disposed
		at org.eclipse.swt.SWT.error(SWT.java:3753)
		at org.eclipse.swt.SWT.error(SWT.java:3676)
		at org.eclipse.swt.SWT.error(SWT.java:3647)
		at org.eclipse.swt.widgets.Widget.error(Widget.java:1018)
		at org.eclipse.swt.widgets.Widget.getDisplay(Widget.java:397)
		at org.eclipse.swt.widgets.Widget.isValidThread(Widget.java:972)
		at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:955)
		at org.eclipse.swt.widgets.ToolBar.getItems(ToolBar.java:207)
		at org.apache.hop.ui.hopgui.HopGui.isActivePerspective(HopGui.java:1598)
		at org.apache.hop.ui.hopgui.perspective.explorer.ExplorerPerspective.isActive(ExplorerPerspective.java:230)
		at org.apache.hop.ui.hopgui.HopGuiKeyHandler.handleKey(HopGuiKeyHandler.java:104)
		at org.apache.hop.ui.hopgui.HopGuiKeyHandler.keyPressed(HopGuiKeyHandler.java:74)
		at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:190)
		at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
		at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
		at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
		at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1216)
		at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1197)
		at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1180)
		at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1172)
		at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
		at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
		at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
		at java.base/java.lang.Thread.run(Thread.java:829)
		at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)```

**Comment by hansva** [comment]
No response from the user, closing this ticket.

**Comment by hungnguyen259** [comment]
Hop web is crashes when I press Ctrl.

**Comment by phamhuyhoang97** [comment]
Any update here @bamaer, @hansva? I pull the latest image (2.6.0-SNAPSHOT) and 2.5.0 for the hop web, but both get the same error. To reproduce:
  1. I docker run the image
  2. Go to the web page on localhost:8080
  3. Refresh the web page
  4. Press the Ctrl button on the keyboard
  => The web page shows the msg "Server Error", and the error keeps going until I recreate the docker container.

Even when I try the [demo server](http://demo.hop.apache.org/ui), it gets the same.
![image](https://github.com/apache/hop/assets/31922679/faad998a-1b83-4551-809a-75bde1f2db32)

**Comment by bamaer** [comment]
we'll look into this for 2.6.0.
gentle reminder: priorities are defined by what Apache Hop developers need, want to work on it are paid to work on. 
software has bugs, and fixing bugs takes time.

**Comment by phamhuyhoang97** [comment]
Thank you @bamaer, hope it can be done in 2.6.0.

**Comment by vutiendung** [comment]
Hi guys,

I have encoutered this issue and here is my temporary solution to fix that issue.

In the file `ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java`
The function: `handleKey`
I have wrapped the the code into the try catch block

```
// If this is attached to a perspective, and it's not active, bail out.
    if (parentObject instanceof IHopPerspective) {
      IHopPerspective perspective = (IHopPerspective) parentObject;
      try {
        if (!perspective.isActive()) {
          return false;
        }
      } catch (Exception ex) {
        return false;
      }
    }
```

Hope this can make your day.
