### ISSUE TITLE
[Bug]: Postgres Bulk Loader throws class exception

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2907]
### Apache Hop version?

2.4-GA

### Java version?

11

### Operating system

Linux

### What happened?

Take a fresh copy of 2.4-GA.  Take any data to the PG Bulk Loader against any PG table and it will throw the following exception.

2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - class org.postgresql.jdbc.PgConnection cannot be cast to class org.postgresql.PGConnection (org.postgresql.jdbc.PgConnection is in unnamed module of loader org.apache.hop.core.plugins.HopURLClassLoader @3eb64e63; org.postgresql.PGConnection is in unnamed module of loader org.apache.hop.core.plugins.HopURLClassLoader @72155315)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoader.doCopy(PGBulkLoader.java:161)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoader.processRow(PGBulkLoader.java:240)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	at java.base/java.lang.Thread.run(Thread.java:829)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - Caused by: java.lang.ClassCastException: class org.postgresql.jdbc.PgConnection cannot be cast to class org.postgresql.PGConnection (org.postgresql.jdbc.PgConnection is in unnamed module of loader org.apache.hop.core.plugins.HopURLClassLoader @3eb64e63; org.postgresql.PGConnection is in unnamed module of loader org.apache.hop.core.plugins.HopURLClassLoader @72155315)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	at org.apache.hop.pipeline.transforms.pgbulkloader.PGBulkLoader.doCopy(PGBulkLoader.java:158)
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - 	... 3 more
2023/05/09 02:12:36 - PostgreSQL Bulk Loader.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
Ciao @usbrandon 

the fix is not that easy but we are working on it. The best solution we foresee for this issue is to move forward with issue #2129 but in the meanwhile, to workaround the problem, move the postgresql jdbc driver out of the plugins/database/postgresql/lib directory to lib/core directory. As I said, this is a temporary workaround in the meanwhile we will fix the things cleanly and definitely.
