### ISSUE TITLE
[Bug]: MongoDB Delete, widget disposed when pressing escape

### ISSUE THREAD

**Issue by hansva** [apache/hop#2971]
### Apache Hop version?

2.5.0-SNAPSHOT (2023-05-24 09.54.30)

### Java version?

11

### Operating system

macOS

### What happened?

When opening the MongoDB Delete transform and pressing escape a widget disposed error is shown.

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
	at org.eclipse.swt.widgets.Decorations.getText(Decorations.java:372)
	at org.apache.hop.ui.core.gui.WindowProperty.<init>(WindowProperty.java:59)
	at org.apache.hop.ui.pipeline.transform.BaseTransformDialog.dispose(BaseTransformDialog.java:283)
	at org.apache.hop.pipeline.transforms.mongodbdelete.MongoDbDeleteDialog.cancel(MongoDbDeleteDialog.java:527)
	at org.apache.hop.pipeline.transforms.mongodbdelete.MongoDbDeleteDialog.lambda$open$8(MongoDbDeleteDialog.java:519)
	at org.apache.hop.ui.core.dialog.BaseDialog.lambda$defaultShellHandling$1(BaseDialog.java:493)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:624)
	at org.eclipse.swt.widgets.Shell.close(Shell.java:618)
	at org.eclipse.swt.widgets.Shell.traverseEscape(Shell.java:2219)
	at org.eclipse.swt.widgets.Control.traverse(Control.java:5043)
	at org.eclipse.swt.widgets.Control.translateTraversal(Control.java:4822)
	at org.eclipse.swt.widgets.Control.keyDown(Control.java:2451)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6324)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2264)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2511)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6444)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5692)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5831)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:515)
	at org.apache.hop.pipeline.transforms.mongodbdelete.MongoDbDeleteDialog.open(MongoDbDeleteDialog.java:519)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3345)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseUp(HopGuiPipelineGraph.java:937)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:474)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)
```

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
.take-issue
