### ISSUE TITLE
[Bug]: Dimension lookup/update cache issue

### ISSUE THREAD

**Issue by kleysonr** [apache/hop#2978]
### Apache Hop version?

2.4.0 (2023-03-27 07.51.24)

### Java version?

openjdk 11.0.19 2023-04-18 LTS

### Operating system

Windows

### What happened?

I'm using the default cache configuration in the Dimension lookup/update transform.

When I have cache enabled, I'm getting the following error:

```
2023/05/29 11:38:29 - Hop - Pipeline opened.
2023/05/29 11:38:29 - Hop - Launching pipeline [d_localidade]...
2023/05/29 11:38:29 - Hop - Started the pipeline execution.
2023/05/29 11:38:30 - d_localidade - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
2023/05/29 11:38:30 - d_localidade - Execution started for pipeline [d_localidade]
2023/05/29 11:38:30 - mei: load municipios.0 - Finished processing (I=5570, O=0, R=0, W=5570, U=0, E=0)
2023/05/29 11:38:30 - so: upper nomes.0 - Finished processing (I=0, O=0, R=5570, W=5570, U=0, E=0)
2023/05/29 11:38:30 - dlu: d_localidade.0 - ERROR: Unexpected error
2023/05/29 11:38:30 - dlu: d_localidade.0 - ERROR: java.lang.NullPointerException
2023/05/29 11:38:30 - dlu: d_localidade.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.getFromCache(DimensionLookup.java:1680)
2023/05/29 11:38:30 - dlu: d_localidade.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.lookupValues(DimensionLookup.java:430)
2023/05/29 11:38:30 - dlu: d_localidade.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:204)
2023/05/29 11:38:30 - dlu: d_localidade.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/05/29 11:38:30 - dlu: d_localidade.0 - 	at java.base/java.lang.Thread.run(Thread.java:829)
2023/05/29 11:38:30 - input.0 - Finished processing (I=0, O=0, R=29924, W=29924, U=0, E=0)
2023/05/29 11:38:30 - sl: lookup cidades.0 - Finished processing (I=0, O=0, R=25593, W=20023, U=0, E=0)
2023/05/29 11:38:30 - De-serialize from file.0 - Finished processing (I=39825, O=0, R=0, W=39825, U=0, E=0)
2023/05/29 11:38:30 - dlu: d_localidade.0 - Finished processing (I=15, O=12, R=16, W=15, U=0, E=1)
2023/05/29 11:38:30 - d_localidade - Pipeline detected one or more transforms with errors.
2023/05/29 11:38:30 - d_localidade - Pipeline is killing the other transforms!
2023/05/29 11:38:31 - output.0 - Finished processing (I=0, O=0, R=15, W=15, U=0, E=0)
2023/05/29 11:38:31 - O QUE FAZER COM ERROS ?.0 - Finished processing (I=0, O=0, R=34, W=34, U=0, E=0)
2023/05/29 11:38:31 - fr: check erros.0 - Finished processing (I=0, O=0, R=10051, W=10051, U=0, E=0)
2023/05/29 11:38:31 - d_localidade - Pipeline duration : 1.042 seconds [  1.042" ]
2023/05/29 11:38:31 - d_localidade - Execution finished on a local pipeline engine with run configuration 'local'
```
The following images are showing the transform configuration and sample data.

![dlu-default-conf-with-cache-error](https://github.com/apache/hop/assets/1976289/11e1dac5-7394-48b4-8261-17bd202abcca)

![sample-data](https://github.com/apache/hop/assets/1976289/00673c21-b9b4-40ca-8c9a-791ee6251cdb)

But when I disable the option 'Enable the cache?' or even set 'Cache size in rows' to '-1', my pipeline runs without any errors.

```
2023/05/29 14:26:10 - Hop - Pipeline opened.
2023/05/29 14:26:10 - Hop - Launching pipeline [d_localidade]...
2023/05/29 14:26:10 - Hop - Started the pipeline execution.
2023/05/29 14:26:10 - d_localidade - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
2023/05/29 14:26:10 - d_localidade - Execution started for pipeline [d_localidade]
2023/05/29 14:26:10 - mei: load municipios.0 - Finished processing (I=5570, O=0, R=0, W=5570, U=0, E=0)
2023/05/29 14:26:10 - so: upper nomes.0 - Finished processing (I=0, O=0, R=5570, W=5570, U=0, E=0)
2023/05/29 14:26:50 - De-serialize from file.0 - Finished processing (I=79207, O=0, R=0, W=79207, U=0, E=0)
2023/05/29 14:26:59 - input.0 - Finished processing (I=0, O=0, R=79207, W=79207, U=0, E=0)
2023/05/29 14:27:09 - sl: lookup cidades.0 - Finished processing (I=0, O=0, R=84777, W=79207, U=0, E=0)
2023/05/29 14:27:18 - fr: check erros.0 - Finished processing (I=0, O=0, R=79207, W=79207, U=0, E=0)
2023/05/29 14:27:18 - O QUE FAZER COM ERROS ?.0 - Finished processing (I=0, O=0, R=140, W=140, U=0, E=0)
2023/05/29 14:27:28 - dlu: d_localidade.0 - Finished processing (I=79067, O=244, R=79067, W=79067, U=0, E=0)
2023/05/29 14:27:28 - output.0 - Finished processing (I=0, O=0, R=79067, W=79067, U=0, E=0)
2023/05/29 14:27:28 - d_localidade - Pipeline duration : 77.944 seconds [  1' 17.944" ]
2023/05/29 14:27:28 - d_localidade - Execution finished on a local pipeline engine with run configuration 'local'
```

### Issue Priority

Priority: 1

### Issue Component

Component: Actions, Component: Database, Component: Transforms

**Comment by kleysonr** [comment]
I'm not dealing with those fields. I have no date field in the stream.

The same source data and step configuration works fine in the latest PDI.

**Comment by nadment** [comment]
Can you try if the latest build fixes your problem ?

**Comment by kleysonr** [comment]
I will try. I had to change all to PDI due to the issue.

**Comment by mattcasters** [comment]
Is this still an issue?  If so, can we have an example that reproduces the problem?  Thanks!

**Comment by pedroarinto** [comment]
I can confirm there is still a problem on 2.7.0 (2023-12-01 10.59.05)
When enabling cache on Dimension Lookup/Update, the following error occurs after some records are processed (the number varies):

```2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - ERROR: Unexpected error
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - ERROR: java.lang.RuntimeException: Error serializing row to byte array
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at org.apache.hop.core.row.RowMeta.extractData(RowMeta.java:1148)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.addToCache(DimensionLookup.java:1566)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.lookupValues(DimensionLookup.java:705)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:204)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 	at java.base/java.lang.Thread.run(Thread.java:829)
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - Caused by: org.apache.hop.core.exception.HopFileException: 
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - date_from None : Unable to serialize data type 0
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 
2024/01/04 16:44:57 - Actualiza dimensao Artigo.0 - 
```

With cache disabled the pipeline executes successfully. The date_from field is using the default values (year 1900).
I'm using the docker container to execute the pipeline. At first we had converted a Kettle transformation to a Hop pipeline, but we re-wrote the pipeline from scratch to test, with the same results.

**Comment by pedroarinto** [comment]
Following up on my previous comment, we have disabled the "Update the dimension" option in the Dimension Lookup/Update action and the pipeline runs successfully, so it seems the error is related to the Dimension update mechanism when cache is enabled (as I wrote previously, with cache disabled the pipeline runs and correctly updates the dimension).

**Comment by hansva** [comment]
Could you add a schema definition and database type for the target please, I'll see if I can create a reproduction path then

**Comment by mattcasters** [comment]
Data type 0 means None. One of the input fields doesn't have a data type. As such it can't be serialized or cached.

**Comment by hansva** [comment]
As it is the date_from in this case it means there must be an issue with the data type coming back from the database. That's why database type and table definition are needed to dig to the root cause.

**Comment by pedroarinto** [comment]
After further testing, it seems the issue is specific for connections using the MSSQL jTDS driver. I've changed the connections to MSSQL (native) and the issue is gone.
Also, i've noticed that when previewing field output from an action (still using the jTDS driver) all Datetime fields show as Type 'None'. With the native driver they show up correctly as 'Timestamp'.

**Comment by mattcasters** [comment]
So this probably a new data type for this older driver and doesn't recognize it. Did you alter the DDL that Hop proposes?

**Comment by hansva** [comment]
It can also be that you have to enable the "supports timestamp" option in the advanced settings of the database connection.

Let's close this issue as the error is clear now.
