### ISSUE TITLE
[Bug]: Salesforce Input transformation errors out when testing the connection

### ISSUE THREAD

**Issue by sunny-thirdeye** [apache/hop#2988]
### Apache Hop version?

2.4.0 (2023-03-27 07.51.24)

### Java version?

openjdk version "11.0.19" 2023-04-18

### Operating system

macOS

### What happened?

Attempting to connect to Salesforce using the input transformation component.

getting the following error:
```
Exception: 
Error connecting to Salesforce!
 at org.apache.hop.ui.hopgui.HopGui.main (HopGui.java:352)
 at org.apache.hop.ui.hopgui.HopGui.open (HopGui.java:474)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3991)
 at org.eclipse.swt.widgets.Display.runAsyncMessages (Display.java:4368)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages (Synchronizer.java:132)
 at org.eclipse.swt.widgets.RunnableLock.run (RunnableLock.java:40)
 at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0 (GuiContextUtil.java:183)
 at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0 (GuiActionLambdaBuilder.java:96)
 at java.lang.reflect.Method.invoke (Method.java:566)
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:2161)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:3345)
 at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform (HopGuiPipelineTransformDelegate.java:174)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.open (SalesforceInputDialog.java:1328)
 at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling (BaseDialog.java:515)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3989)
 at org.eclipse.swt.widgets.Display.runDeferredEvents (Display.java:4413)
 at org.eclipse.swt.widgets.Widget.notifyListeners (Widget.java:1325)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1532)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1547)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1524)
 at org.eclipse.swt.widgets.Display.sendEvent (Display.java:4646)
 at org.eclipse.swt.widgets.EventTable.sendEvent (EventTable.java:89)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.lambda$open$7 (SalesforceInputDialog.java:1313)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceTransformDialog.test (SalesforceTransformDialog.java:69)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceConnection.connect (SalesforceConnection.java:339)
 at com.sforce.soap.partner.PartnerConnection.getUserInfo (PartnerConnection.java:574)
 at com.sforce.ws.transport.SoapConnection.send (SoapConnection.java:108)
 at com.sforce.ws.transport.SoapConnection.receive (SoapConnection.java:163)
 at com.sforce.ws.transport.SoapConnection.createException (SoapConnection.java:224)
 at com.sforce.ws.transport.SoapConnection.parseDetail (SoapConnection.java:250)
 at com.sforce.ws.bind.TypeMapper.readObject (TypeMapper.java:593)
 at com.sforce.ws.bind.TypeMapper.readSingle (TypeMapper.java:721)
 at java.lang.Class.newInstance (Class.java:584)
 at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
 at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)

Root cause: Exception: 
Error connecting to Salesforce!
 at org.apache.hop.ui.hopgui.HopGui.main (HopGui.java:352)
 at org.apache.hop.ui.hopgui.HopGui.open (HopGui.java:474)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3991)
 at org.eclipse.swt.widgets.Display.runAsyncMessages (Display.java:4368)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages (Synchronizer.java:132)
 at org.eclipse.swt.widgets.RunnableLock.run (RunnableLock.java:40)
 at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0 (GuiContextUtil.java:183)
 at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0 (GuiActionLambdaBuilder.java:96)
 at java.lang.reflect.Method.invoke (Method.java:566)
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:2161)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:3345)
 at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform (HopGuiPipelineTransformDelegate.java:174)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.open (SalesforceInputDialog.java:1328)
 at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling (BaseDialog.java:515)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3989)
 at org.eclipse.swt.widgets.Display.runDeferredEvents (Display.java:4413)
 at org.eclipse.swt.widgets.Widget.notifyListeners (Widget.java:1325)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1532)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1547)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1524)
 at org.eclipse.swt.widgets.Display.sendEvent (Display.java:4646)
 at org.eclipse.swt.widgets.EventTable.sendEvent (EventTable.java:89)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.lambda$open$7 (SalesforceInputDialog.java:1313)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceTransformDialog.test (SalesforceTransformDialog.java:69)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceConnection.connect (SalesforceConnection.java:339)
 at com.sforce.soap.partner.PartnerConnection.getUserInfo (PartnerConnection.java:574)
 at com.sforce.ws.transport.SoapConnection.send (SoapConnection.java:108)
 at com.sforce.ws.transport.SoapConnection.receive (SoapConnection.java:163)
 at com.sforce.ws.transport.SoapConnection.createException (SoapConnection.java:224)
 at com.sforce.ws.transport.SoapConnection.parseDetail (SoapConnection.java:250)
 at com.sforce.ws.bind.TypeMapper.readObject (TypeMapper.java:593)
 at com.sforce.ws.bind.TypeMapper.readSingle (TypeMapper.java:721)
 at java.lang.Class.newInstance (Class.java:584)
 at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
 at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
```

when clicking on "Details", seeing this additional stack trace
```
java.lang.Exception: 
Error connecting to Salesforce!
 at org.apache.hop.ui.hopgui.HopGui.main (HopGui.java:352)
 at org.apache.hop.ui.hopgui.HopGui.open (HopGui.java:474)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3991)
 at org.eclipse.swt.widgets.Display.runAsyncMessages (Display.java:4368)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages (Synchronizer.java:132)
 at org.eclipse.swt.widgets.RunnableLock.run (RunnableLock.java:40)
 at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0 (GuiContextUtil.java:183)
 at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0 (GuiActionLambdaBuilder.java:96)
 at java.lang.reflect.Method.invoke (Method.java:566)
 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:2161)
 at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform (HopGuiPipelineGraph.java:3345)
 at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform (HopGuiPipelineTransformDelegate.java:174)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.open (SalesforceInputDialog.java:1328)
 at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling (BaseDialog.java:515)
 at org.eclipse.swt.widgets.Display.readAndDispatch (Display.java:3989)
 at org.eclipse.swt.widgets.Display.runDeferredEvents (Display.java:4413)
 at org.eclipse.swt.widgets.Widget.notifyListeners (Widget.java:1325)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1532)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1547)
 at org.eclipse.swt.widgets.Widget.sendEvent (Widget.java:1524)
 at org.eclipse.swt.widgets.Display.sendEvent (Display.java:4646)
 at org.eclipse.swt.widgets.EventTable.sendEvent (EventTable.java:89)
 at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.lambda$open$7 (SalesforceInputDialog.java:1313)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceTransformDialog.test (SalesforceTransformDialog.java:69)
 at org.apache.hop.pipeline.transforms.salesforce.SalesforceConnection.connect (SalesforceConnection.java:339)
 at com.sforce.soap.partner.PartnerConnection.getUserInfo (PartnerConnection.java:574)
 at com.sforce.ws.transport.SoapConnection.send (SoapConnection.java:108)
 at com.sforce.ws.transport.SoapConnection.receive (SoapConnection.java:163)
 at com.sforce.ws.transport.SoapConnection.createException (SoapConnection.java:224)
 at com.sforce.ws.transport.SoapConnection.parseDetail (SoapConnection.java:250)
 at com.sforce.ws.bind.TypeMapper.readObject (TypeMapper.java:593)
 at com.sforce.ws.bind.TypeMapper.readSingle (TypeMapper.java:721)
 at java.lang.Class.newInstance (Class.java:584)
 at java.lang.reflect.Constructor.newInstance (Constructor.java:490)
 at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:62)
 at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)

	at org.apache.hop.pipeline.transforms.salesforce.SalesforceTransformDialog.test(SalesforceTransformDialog.java:95)
	at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.lambda$open$7(SalesforceInputDialog.java:1313)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:515)
	at org.apache.hop.pipeline.transforms.salesforceinput.SalesforceInputDialog.open(SalesforceInputDialog.java:1328)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3345)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4368)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3991)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:474)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)

```

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
Ciao @sunny-thirdeye let us know in case you need help in investigating the issue.

**Comment by sunny-thirdeye** [comment]
solved.

The error wasn't a catchable `LoginFault`

I have fixed the problem by adding a "dumb" console output of the error in the final `catch (Exception e)` statement of the login attempt. I would actually raise a PR and fix this in a better way, but don't know how to make the error show up in the UI 😂
