### ISSUE TITLE
[Bug]: Flink error can't be deserialized ClassNotFoundException: org.apache.flink.util.SerializedThrowable

### ISSUE THREAD

**Issue by mkhludnev** [apache/hop#2997]
### Apache Hop version?

2.4, master

### Java version?

11

### Operating system

Windows

### What happened?

I run a simple pipeline with Flink runner, it fails due to some reason. This failure is not a problem. But the error from flink can't be returned back to Hop see below. I suppose the root cause is `ClassNotFoundException: org.apache.flink.util.SerializedThrowable`. Does it seem like a classpath error? 

```
..
Caused by: java.util.concurrent.CompletionException: org.apache.flink.runtime.rest.util.RestClientException: Response was neither of the expected type([simple type, class org.apache.flink.runtime.rest.messages.job.JobExecutionResultResponseBody]) nor an error.
 at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
 at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
 at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
 ... 4 more
Caused by: org.apache.flink.runtime.rest.util.RestClientException: Response was neither of the expected type([simple type, class org.apache.flink.runtime.rest.messages.job.JobExecutionResultResponseBody]) nor an error.

 at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:548)
 at org.apache.flink.runtime.rest.RestClient.lambda$submitRequest$3(RestClient.java:512)
 at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
 ... 4 more
Caused by: java.io.IOException: Failed to deserialize org.apache.flink.util.SerializedThrowable
 at org.apache.flink.runtime.rest.messages.json.SerializedThrowableDeserializer.deserialize(SerializedThrowableDeserializer.java:53)
 at org.apache.flink.runtime.rest.messages.json.JobResultDeserializer.deserialize(JobResultDeserializer.java:106)
 at org.apache.flink.runtime.rest.messages.json.JobResultDeserializer.deserialize(JobResultDeserializer.java:50)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:565)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:449)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4569)
 at org.apache.flink.shaded.jackson2.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
 at org.apache.flink.runtime.rest.RestClient.parseResponse(RestClient.java:521)
 ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.util.SerializedThrowable
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
 at java.base/java.lang.Class.forName0(Native Method)
 at java.base/java.lang.Class.forName(Class.java:467)
 at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
 at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2034)
 at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
 at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
 at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
 at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
 at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
 at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
 at org.apache.flink.runtime.rest.messages.json.SerializedThrowableDeserializer.deserialize(SerializedThrowableDeserializer.java:49)
 ... 18 more
```
 

### Issue Priority

Priority: 3

### Issue Component

Component: Beam

**Comment by mattcasters** [comment]
Hi @mkhludnev , thanks for testing this. 
Did you generate a fat jar with Hop as shown in the documentation, use flink run, ...? Could you prova bit more context?

https://hop.apache.org/manual/latest/pipeline/pipeline-run-configurations/beam-flink-pipeline-engine.html

Thanks,

Matt

**Comment by mkhludnev** [comment]
Ahh. thanks. 

1. Right, I miss that fat.jar. 
2. Terribly sorry for turning this issue into mailing list thread.
3. I tried to use `flink run` got some issue below. 
4. I'm on windows+WSL, I already fixed some incompatibilities. But I'm giving up and switching to Linux now.
5. Anyway here the question:

```
$ bin/flink run --class org.apache.hop.beam.run.MainBeam -D PROJECT_HOME=/mnt/c/Users/user/hop/config/projects/samples /mnt/c/Users/user/hop/config/projects/samples/filename.jar /mnt/c/Users/user/hop/config/projects/samples/beam/pipelines/generate-synthetic-data.hpl /mnt/c/Users/user/hop/config/projects/samples/filename.json Flink 
```

here's the output 

```
>>>>>> Initializing Hop
Hop configuration file not found, not serializing: /mnt/c/Users/user/flink-1.13.0/config/hop-config.json
```

^ that's wrong. I havent' found a way to pass project config there. How to do that? 
Remaining lines seem fine. 
 
```
Argument 1 : Pipeline filename (.hpl)   : /mnt/c/Users/user/hop/config/projects/samples/beam/pipelines/generate-synthetic-data.hpl
Argument 2 : Environment state filename: (.json)  : /mnt/c/Users/user/hop/config/projects/samples/filename.json
Argument 3 : Pipeline run configuration : Flink
>>>>>> Loading pipeline metadata
>>>>>> Building Apache Beam Pipeline...
>>>>>> Pipeline executing starting...
2023/06/08 14:09:05 - General - Created Apache Beam pipeline with name 'generate-synthetic-data'
```

However, then: 

```
023/06/08 14:09:10 - General - Executing this pipeline using the Beam Pipeline Engine with run configuration 'Flink'
2023/06/08 14:09:10 - General - ERROR: Error starting the Beam pipeline
2023/06/08 14:09:10 - General - ERROR: org.apache.hop.core.exception.HopException:
2023/06/08 14:09:10 - General - Error executing pipeline with runner Flink
2023/06/08 14:09:10 - General - The RemoteEnvironment cannot be instantiated when running in a pre-defined context (such as Command Line Client, Scala Shell, or TestEnvironment)
2023/06/08 14:09:10 - General -
2023/06/08 14:09:10 - General -         at org.apache.hop.beam.engines.BeamPipelineEngine.executePipeline(BeamPipelineEngine.java:319)
2023/06/08 14:09:10 - General -         at org.apache.hop.beam.engines.BeamPipelineEngine.startThreads(BeamPipelineEngine.java:345)
2023/06/08 14:09:10 - General -         at org.apache.hop.beam.engines.BeamPipelineEngine.execute(BeamPipelineEngine.java:635)
2023/06/08 14:09:10 - General -         at org.apache.hop.beam.run.MainBeam.main(MainBeam.java:150)
2023/06/08 14:09:10 - General - Caused by: org.apache.flink.api.common.InvalidProgramException: The RemoteEnvironment cannot be instantiated when running in a pre-defined context (such as Command Line Client, Scala Shell, or TestEnvironment)
2023/06/08 14:09:10 - General -         at org.apache.flink.api.java.RemoteEnvironmentConfigUtils.validate(RemoteEnvironmentConfigUtils.java:52)
2023/06/08 14:09:10 - General -         at org.apache.flink.api.java.RemoteEnvironment.validateAndGetEffectiveConfiguration(RemoteEnvironment.java:116)
2023/06/08 14:09:10 - General -         at org.apache.flink.api.java.RemoteEnvironment.<init>(RemoteEnvironment.java:106)
2023/06/08 14:09:10 - General -         at org.apache.flink.api.java.ExecutionEnvironment.createRemoteEnvironment(ExecutionEnvironment.java:1362)
2023/06/08 14:09:10 - General -         at org.apache.beam.runners.flink.FlinkExecutionEnvironments.createBatchExecutionEnvironment(FlinkExecutionEnvironments.java:103)
2023/06/08 14:09:10 - General -         at org.apache.beam.runners.flink.FlinkExecutionEnvironments.createBatchExecutionEnvironment(FlinkExecutionEnvironments.java:67)
2023/06/08 14:09:10 - General -         at org.apache.beam.runners.flink.FlinkPipelineExecutionEnvironment.translate(FlinkPipelineExecutionEnvironment.java:107)
2023/06/08 14:09:10 - General -         at org.apache.beam.runners.flink.FlinkRunner.run(FlinkRunner.java:104)
2023/06/08 14:09:10 - General -         at org.apache.hop.beam.engines.BeamPipelineEngine.executePipeline(BeamPipelineEngine.java:309)
2023/06/08 14:09:10 - General -         ... 16 more
```

I read it as: in the command line context we can't connect to another Flink cluster, but that's what Hop's MainBeam attempts to do. How should it work? Did I miss something?

**Comment by mattcasters** [comment]
"pass project config there" 

The project folder as a reference point has no meaning in a clustered context so we don't support it right now.  You can pass in a filename containing variables to help you out.

The flink error basically means you need to run "flink run" on the cluster itself so it can properly distribute the fat jar etc.

Good luck, 

Matt

**Comment by mkhludnev** [comment]
Assuming I'm doing something wrong, despite of that I've found  `org.apache.flink.util.SerializedThrowable` in fat jar. It means if  beam includes fat.jar indo deserializer classpath it can read and display an error originated in Flink. WDYT?

**Comment by mattcasters** [comment]
Like I mentioned earlier, I have no further details concerning your environment.  The details often matter with these clustered environments.  That being said, [a guide](https://hop.apache.org//manual/latest/pipeline/beam/beam-samples-flink.html) was written for this particular case, to get you started.

In my case I have a script that runs:

```
bin/flink run \
  --class org.apache.hop.beam.run.MainBeam \
  /tmp/hop-fatjar.jar \
  /home/matt/git/mattcasters/hop/assemblies/client/target/hop/config/projects/samples/beam/pipelines/generate-synthetic-data.hpl \
  hop-metadata.json \
  Flink \
  environment.json
  
```

It started all right:

![image](https://github.com/apache/hop/assets/1724620/4a281074-ec94-4874-83c5-97d7a4218f94)

**Comment by mattcasters** [comment]
I'm sorry you didn't find the compatibility table but it was the first thing mentioned in the guide I linked to earlier:

https://hop.apache.org//manual/latest/pipeline/beam/getting-started-with-beam.html#supportedversions
