### ISSUE TITLE
Filter Rows component doesn't handle Date properly 

### ISSUE THREAD

**Issue by duursma** [apache/hop#3051]
### Apache Hop version?

2.5

### Java version?

openjdk version "19.0.1" 2022-10-18

### Operating system

Windows

### What happened?

I want to test a date field against a date constant in the "Filter Rows" component.
For this you have to provide a string and a format.  But it seems the String is saved as a date in an internal format and the verified against the supplied format on testing.  And those two don't necessarily match.

Test case a data grid with a date field.  And a filter rows component with to dummy's as exits.  Test against a date with a yyyy-MM-dd format.

2023/07/03 16:15:22 - Filter rows.0 - ERROR: Unexpected error found in evaluation function :
2023/07/03 16:15:22 - Filter rows.0 - ERROR: Error occurred for row: [01-01-2023]
2023/07/03 16:15:22 - Filter rows.0 - ERROR: java.lang.RuntimeException: Unexpected error evaluation condition [              date < [2022/01/01 00:00:00.000]
2023/07/03 16:15:22 - Filter rows.0 - ]
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.Condition.evaluate(Condition.java:565)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.pipeline.transforms.filterrows.FilterRows.keepRow(FilterRows.java:51)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.pipeline.transforms.filterrows.FilterRows.processRow(FilterRows.java:122)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/07/03 16:15:22 - Filter rows.0 -   at java.base/java.lang.Thread.run(Thread.java:834)
2023/07/03 16:15:22 - Filter rows.0 - Caused by: org.apache.hop.core.exception.HopValueException:
2023/07/03 16:15:22 - Filter rows.0 - constant String : couldn't convert string [2022/01/01 00:00:00.000] to a date using format [yyyy-MM-dd] on offset location 4
2023/07/03 16:15:22 - Filter rows.0 - 2022/01/01 00:00:00.000
2023/07/03 16:15:22 - Filter rows.0 -
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.row.value.ValueMetaBase.convertStringToDate(ValueMetaBase.java:1082)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.row.value.ValueMetaBase.getDate(ValueMetaBase.java:2578)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.row.value.ValueMetaBase.convertDataUsingConversionMetaData(ValueMetaBase.java:4246)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.Condition$CValue.createValueData(Condition.java:917)
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.Condition.evaluate(Condition.java:404)
2023/07/03 16:15:22 - Filter rows.0 -   ... 4 more
2023/07/03 16:15:22 - Filter rows.0 - Caused by: java.text.ParseException: 2022/01/01 00:00:00.000
2023/07/03 16:15:22 - Filter rows.0 -   at org.apache.hop.core.row.value.ValueMetaBase.convertStringToDate(ValueMetaBase.java:1065)
2023/07/03 16:15:22 - Filter rows.0 -   ... 8 more

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Run

**Comment by sramazzina** [comment]
Hi @duursma, can you please provide your exact test case? Moreover, I noticed you are performing your test with jdk 19 but it would be nice to have the same test performed with JDK 11 that is the Hop's supported version.

**Comment by nadment** [comment]
Could you try with format [yyyy/MM/dd] according to  your string [2022/01/01 00:00:00.000] instead of [yyyy-MM-dd]

**Comment by duursma** [comment]
Actually the jdk already was jdk-11.  Something went wrong in the step to create the running environment.  Environment is set in a startup-script.
Java identified as "c:\Java\jdk-11\bin\java"

Using the yyy/MM/dd format works.  So that seems consistent with my suggesting.   Pattern is applied to string and converted to a date string in a standard format.  Then on using it the converted string is applied to the original pattern and fails.

Reproduction scenario:
- new pipeline
- add datagrid
- add to datagrid field 'date' type Date format 'mm-DD-yyyy'
- add do datagrid value '01-01-2022'
- add filter rows
- add dummy as true
- add dummy as false
- edit filter
- speciify date field
- specify operator '<'
- specify a format 'yyyy-MM-dd'
- specify a value '2021-01-01'
- run the pipeline

Expected results and error message sometimes combined with a hanging user interface.

**Comment by nadment** [comment]
I tried your scenario and it works well, see the pipeline. What did I miss?

[3051.zip](https://github.com/apache/hop/files/11951951/3051.zip)

**Comment by duursma** [comment]
Can't be sure but from the looks the 'right' format/mask of the date in the 'filter' was used.

I use format 'yyyy-MM-dd'.  After saving and opening the shown date has format yyyy/MM/dd .... 
On selecting that field I get the error:
HopValueException: 
constant String : couldn't convert string [2023/02/02 00:00:00.000] to a date using format [yyyy-MM-dd] on offset location 4
2023/02/02 00:00:00.000

Root cause: ParseException: 2023/02/02 00:00:00.000

Where in your version I just get a popup showing the date and the format both being 'yyyy/MM/dd ... '

Differences in the xml files:
Mine:
        <value>
          <isnull>N</isnull>
          <length>-1</length>
          <mask>yyyy-MM-dd</mask>
          <name>constant</name>
          <precision>-1</precision>
          <text>2023/02/02 00:00:00.000</text>
          <type>Date</type>
        </value>

Yours:
        <value>
          <isnull>N</isnull>
          <length>-1</length>
          <mask>yyyy/MM/dd</mask>
          <name>constant</name>
          <precision>-1</precision>
          <text>2023/01/01 00:00:00.000</text>
          <type>Date</type>
        </value>

So the date is entered according to the mask, but stored as text using a different mask.
