### ISSUE TITLE
[Bug]: removing workflow logging entry and file causes errors in Execution Information

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3078]
### Apache Hop version?

2.4

### Java version?

microsoft-jdk-11.0.19-windows-x64.msi

### Operating system

Windows

### What happened?

dan
[9:25 AM](https://chat.project-hop.org/hop/pl/8y6odma5mtd55jk799mmjn84ma)

I think I removed workflow logging in an incorrect way, possibly?

1. I deleted the Workflow logging entry under Workflow Log in MetaData (Ctrl+Shift+M)
2. I deleted the "logging" folder that included the workflow logging file
3. I opened Execution Information and it had many errors (screenshot and details in chat)
4. I restarted Hop but still has errors
5. I recreated an empty logging folder but still has errors
6. I restarted Hop but still has errors

![image](https://github.com/apache/hop/assets/100213981/bb1d17db-fb38-4eeb-9d03-6862bc30bb56)

**Details**:
org.apache.hop.core.exception.HopException: 
Error getting execution from Neo4j
Name is null

at org.apache.hop.neo4j.execution.NeoExecutionInfoLocation.getExecution(NeoExecutionInfoLocation.java:531)
at org.apache.hop.ui.hopgui.perspective.execution.ExecutionPerspective.refresh(ExecutionPerspective.java:549)
at org.apache.hop.ui.hopgui.perspective.execution.ExecutionPerspective.perspectiveActivated(ExecutionPerspective.java:151)
at org.apache.hop.ui.hopgui.HopGui.setActivePerspective(HopGui.java:1591)
at org.apache.hop.ui.hopgui.HopGui.lambda$loadPerspectives$2(HopGui.java:523)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:474)
at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)
Caused by: java.lang.NullPointerException: Name is null
    at java.base/java.lang.Enum.valueOf(Enum.java:238)
    at org.apache.hop.execution.ExecutionType.valueOf(ExecutionType.java:21)
    at org.apache.hop.neo4j.execution.NeoExecutionInfoLocation.getNeo4jExecution(NeoExecutionInfoLocation.java:568)
    at org.apache.hop.neo4j.execution.NeoExecutionInfoLocation.lambda$getExecution$2(NeoExecutionInfoLocation.java:529)
    at org.neo4j.driver.internal.InternalSession.lambda$transaction$4(InternalSession.java:137)
    at org.neo4j.driver.internal.retry.ExponentialBackoffRetryLogic.retry(ExponentialBackoffRetryLogic.java:106)
    at org.neo4j.driver.internal.InternalSession.transaction(InternalSession.java:134)
    at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:103)
    at org.neo4j.driver.internal.InternalSession.readTransaction(InternalSession.java:98)
    at org.apache.hop.neo4j.execution.NeoExecutionInfoLocation.getExecution(NeoExecutionInfoLocation.java:529)
    ... 11 more

### Issue Priority

Priority: 3

### Issue Component

Component: Metadata

**Comment by Mattang-Dan** [comment]
I neglected to mention that I only followed Step 1: from

[Workflow Log :: Apache Hop](https://hop.apache.org/manual/next/how-to-guides/logging-workflow-log.html)

**Comment by Mattang-Dan** [comment]
Now I am starting to doubt myself, I don't look at Execution Information all that much, what if these errors were there earlier? hmmm.... My workflow and pipelines run fine.


I did also notice yesterday when I was re-ordering tabs (pipelines), that sometimes all of a sudden 2 tabs had identical objects on them (with different tab names), the one that moved and the tab in the old position I think. This happened several times.

**Comment by Mattang-Dan** [comment]
As a side note, I was advised to use local file Execution Information Location logging instead of to Neo4j.

**Comment by mattcasters** [comment]
Logging to files is eventually consistent and the Neo4j implementation should be transactional.  It's always possible that deleting execution nodes doesn't work correctly.  However, a proper reproduction path is really necessary to fix this.  Thanks in advance.
