### ISSUE TITLE
[Bug]: No more project reload after env change

### ISSUE THREAD

**Issue by enricomariam42** [apache/hop#3169]
### Apache Hop version?

2.6.0-20230818.084735-1

### Java version?

openjdk 11.0.9.1 2020-11-04

### Operating system

Linux

### What happened?

There is no more alert after changing the env properties and the variables are not updated anymore. 
The log report the error:
```
GUI - ERROR: Unable to call method editSelectedEnvironment in class org.apache.hop.projects.gui.ProjectsGuiPlugin : null
```

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by mattcasters** [comment]
Confirmed. Are you working on this @sramazzina ?

**Comment by mattcasters** [comment]
ProjectsGuiPlugin:576 : `hopGui.getDisplay().getActiveShell()` is null so the error dialog doesn't pop up.

Original error comes from:

```
java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.java:4899)
at org.eclipse.swt.SWT.error(SWT.java:4833)
at org.eclipse.swt.SWT.error(SWT.java:4804)
at org.eclipse.swt.widgets.Dialog.error(Dialog.java:202)
at org.eclipse.swt.widgets.Dialog.checkParent(Dialog.java:168)
at org.eclipse.swt.widgets.Dialog.<init>(Dialog.java:131)
at org.apache.hop.ui.core.dialog.MessageBox.<init>(MessageBox.java:59)
at org.apache.hop.projects.gui.ProjectsGuiPlugin.askAboutProjectRefresh(ProjectsGuiPlugin.java:181)
at org.apache.hop.projects.gui.ProjectsGuiPlugin.editEnvironment(ProjectsGuiPlugin.java:569)
at org.apache.hop.projects.gui.ProjectsGuiPlugin.editSelectedEnvironment(ProjectsGuiPlugin.java:636)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:216)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473)
at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
```

so ProjectsGuiPlugin, again `hopGui.getDisplay().getActiveShell()`.

Broken by #2944, needs to be hardened or code reverted.

**Comment by sramazzina** [comment]
No @mattcasters I was very busy during last 2 months. Starting to work on the issues from this week but I'm more than hapy to leva this issue to you :-)
