### ISSUE TITLE
[Bug]: Trying to use generic db with duckdb driver 0.9.1

### ISSUE THREAD

**Issue by JonathanLoscalzo** [apache/hop#3354]
### Apache Hop version?

2.6.0

### Java version?

Openjdk version "11.0.20.1" 2023-08-24

### Operating system

Linux

### What happened?

Hi!

I want to use hop with duckdb. The hop-duckdb integration has duckdb's v0.7, but I'd like to use the 0.9.1 (latest).

Trying to configure the Generic Database driver and I could have the ability to read the driver from the folders /hop/lib/<duckdb-jar> or HOP_SHARED_JDBC_FOLDER/<duckdb-jar>. 

It always shows me the following view:
![Captura desde 2023-11-04 13-53-27](https://github.com/apache/hop/assets/6944598/fc30c500-439b-4a56-98e1-7318f88a0463)

and the error is:
```
Error connecting to database [dwh] :org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Driver class 'org.duckdb.DuckDBDriver' could not be found, make sure the 'Generic database' driver (jar file) is installed.
Unable to load class 'org.duckdb.DuckDBDriver' in this classloader or in the parent


org.apache.hop.core.exception.HopDatabaseException: 
Error occurred while trying to connect to the database

Driver class 'org.duckdb.DuckDBDriver' could not be found, make sure the 'Generic database' driver (jar file) is installed.
Unable to load class 'org.duckdb.DuckDBDriver' in this classloader or in the parent
```

As a final note, putting the same driver in pdi at /pdi/lib ~works correctly.~ sometimes shows the information and sometimes no. I think that is a lock issue in pdi. BTW, I want to use Hop.

![Captura desde 2023-11-04 14-02-45](https://github.com/apache/hop/assets/6944598/a94edbd4-86ef-4d01-afc8-8193143ce372)

It could be some "colliding names"?

### Issue Priority

Priority: 3

### Issue Component

Component: Database

**Comment by hansva** [comment]
you can just drop in the 9.X version under plugins/databases/duckdb/lib.
It will be upgraded in the next release

**Comment by JonathanLoscalzo** [comment]
@hansva I have to remove the v0.7 and it works. 

But using the "Dimension Lookup/update" step it does not work with duckdb:

- the generated sql has erros:
```sql
CREATE TABLE warehouse.dim_payment
(
  payment_pk IDENTITY -- HERE: not correct, it should be INTEGER PRIMARY KEY
, version INTEGER
, date_from TIMESTAMP -- HERE I don't know why it could not be generated, bellow I have added the error
, date_to TIMESTAMP -- HERE
, payment_id INTEGER
, customer_id SMALLINT
, staff_id SMALLINT
, rental_id INTEGER
, amount DECIMAL(5, 2)
)
;CREATE INDEX idx_dim_payment_lookup ON warehouse.dim_payment(payment_id)
;
CREATE BITMAP INDEX idx_dim_payment_tk ON warehouse.dim_payment(payment_pk)
;
```
- error when running the step on audit columns (date_from and date_to). 
```

ERROR: Because of an error this transform can't continue: 
offending row : [payment_id Integer(9)], [date_from Date], [date_to Date]

Error setting value #2 [Date] on prepared statement
setTimestamp
ERROR: org.apache.hop.core.exception.HopDatabaseException: 
offending row : [payment_id Integer(9)], [date_from Date], [date_to Date]

Error setting value #2 [Date] on prepared statement
setTimestamp
	at org.apache.hop.core.database.Database.setValues(Database.java:922)
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.lookupValues(DimensionLookup.java:437)
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:204)
	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.hop.core.exception.HopDatabaseException: 
Error setting value #2 [Date] on prepared statement
setTimestamp
	at org.apache.hop.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5693)
	at org.apache.hop.core.database.Database.setValue(Database.java:905)
	at org.apache.hop.core.database.Database.setValues(Database.java:920)
	... 4 more
Caused by: java.sql.SQLFeatureNotSupportedException: setTimestamp
	at org.duckdb.DuckDBPreparedStatement.setTimestamp(DuckDBPreparedStatement.java:770)
	at org.apache.hop.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5644)
	... 6 more
```

- if a field is a timestamp, the error is the same.

**Comment by hansva** [comment]
the generate sql is just a suggestion I honestly never use it. we can take a look at it

**Comment by JonathanLoscalzo** [comment]
> the generate sql is just a suggestion I honestly never use it. we can take a look at it

No problem with the generated sql.

Looking more in depth into logging, I think that the issue is how the query in "Lookup/update" is being prepared:

```
lookup row : [123158], [2023/11/04 18:17:19.143], [2023/11/04 18:17:19.143]
ERROR: Because of an error this transform can't continue: 
offending row : [payment_id Integer(9)], [date_from Date], [date_to Date]
```

I guess that duckdb (I don't know other db's) needs the format Y

**Comment by hansva** [comment]
Interesting, thanks for the feedback. I'll try and take a look at it asap so we can include the fixes in our upcoming release. Should be for the very near future.

**Comment by hansva** [comment]
.take-issue
