### ISSUE TITLE
[Bug]: Null Pointer Exception when Pushing to Remote Respository

### ISSUE THREAD

**Issue by jermjensen** [apache/hop#3485]
### Apache Hop version?

2.7

### Java version?

Oracle JDK 11.0.19

### Operating system

Windows

### What happened?

Within hop-gui, after committing code to a local repository, the user pushes to a GitLab remote server using the Push icon within the File Explorer and the following exception appears:

```
HopException: 
There was an error doing a git push
git@<SERVERNAME>:<STUB>/<GIT REPO NAME>.git: remote hung up unexpectedly

Root cause: NullPointerException: 

When clicking Details for the complete trace, the following appears:

org.apache.hop.core.exception.HopException: 
There was an error doing a git push
git@<SERVERNAME>:<STUB>/<GIT REPO NAME>.git: remote hung up unexpectedly

	at org.apache.hop.git.model.UIGit.push(UIGit.java:582)
	at org.apache.hop.git.model.UIGit.push(UIGit.java:528)
	at org.apache.hop.git.GitGuiPlugin.gitPush(GitGuiPlugin.java:227)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@<SERVERNAME>:<STUB>/<GIT REPO NAME>.git: remote hung up unexpectedly
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:168)
	at org.apache.hop.git.model.UIGit.push(UIGit.java:570)
	... 14 more
Caused by: org.eclipse.jgit.errors.TransportException: git@<SERVERNAME>:<STUB>/<GIT REPO NAME>.git: remote hung up unexpectedly
	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:380)
	at org.eclipse.jgit.transport.TransportGitSsh.openPush(TransportGitSsh.java:157)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:140)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1540)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:158)
	... 15 more
Caused by: java.lang.NullPointerException
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
	at org.eclipse.jgit.transport.TransportGitSsh$SshPushConnection.<init>(TransportGitSsh.java:356)
	... 19 more

```
 

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
SSH repositories are currently not supported, only HTTP(s) ones

**Comment by hansva** [comment]
#2869 is duplicate from this one

**Comment by NicoDupont** [comment]
same probleme with 2.10 and 2.11. 
but if it's not supported, then it's normal

**Comment by bamaer** [comment]
.take-issue
