### ISSUE TITLE
After refreshing hop -gui when click on javascript it throws IllegalArgumentException: Argument not valid Root cause: IllegalArgumentException: Argument not valid[Bug]: 

### ISSUE THREAD

**Issue by poonam541** [apache/hop#3508]
### Apache Hop version?

2.6.0

### Java version?

11.0.21

### Operating system

Windows

### What happened?

After timeout happend when I reload the hop -gui when on javascript it throws below error

 IllegalArgumentException: Argument not valid Root cause: IllegalArgumentException: Argument not valid

could anybody please let me know how to fix this I am running apache hopweb in kubernetes container.

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Web, Component: Pipelines, Component: Transforms

**Comment by wwaechter** [comment]
The behaviour is as followed: 
1. Starting the hop-web container
2. creating/opening a pipeline
3. creating a JavaScript component
4. editing the component from 3. -> it works fine
5. reloading the page in the browser or waiting for time out of the session
6. trying to edit JavaScript component: it fails to open the Edit-Dialog with following error:

java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:3739)
        at org.eclipse.swt.SWT.error(SWT.java:3676)
        at org.eclipse.swt.SWT.error(SWT.java:3647)
        at org.eclipse.swt.widgets.Item.setImage(Item.java:156)
        at org.eclipse.swt.widgets.MenuItem.setImage(MenuItem.java:278)
        at org.apache.hop.pipeline.transforms.javascript.ScriptValuesDialog.buildingFolderMenu(ScriptValuesDialog.java:1657)
        at org.apache.hop.pipeline.transforms.javascript.ScriptValuesDialog.open(ScriptValuesDialog.java:470)
        at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransfo
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3400)
        at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:96)
        at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:183)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:193)
        at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1200)
        at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1180)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1172)
        at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)

I've tested it in three different environments: 
1. Kubernetes environment used by @poonam541: the error can be reproduced
2. Kubernetes from DigitalOcean: the error can't be reproduced
3. Container running on Ubuntu Linux access from a Windows-Client (Chrome) in the same Network: the error can be reproduces 
In cases 1. and 2. the Hop-Web was accessed from the same Windows PC

I've tested it with Hop-Web versions 2.6.0, 2.7.0, 2.8.0, and latest snapshot

**Comment by shlxue** [comment]
This bug is caused by the compatibility of the Image class with the implementation of rwt: SWT. IMAGE_COPY don't work in the RWT library

image = new Image(display, img.getAsBitmapForSize(display, newSize, newSize), SWT. IMAGE_COPY);

I report a issue to eclipse-rap: https://github.com/eclipse-rap/org.eclipse.rap/issues/271

**Comment by shlxue** [comment]
@hansva close the issue?

**Comment by shlxue** [comment]
@hansva Before the eclipse-rap/org.eclipse.rap#271 fixed, only temporary fixing for rwt: don't call dispose method

**Comment by woutersf** [comment]
I'm still having this (it blocks all javascript transforms for me). 
workaround
1. Restart of the application
2. delet the broken js transform
3. recreate the js transform (without breaking it)

**Comment by shlxue** [comment]
@woutersf Hop web version?

**Comment by hansva** [comment]
.take-issue
