### ISSUE TITLE
[Bug]: DuckDB- If you send it a Date some kind of setTimestamp() prepared function fails.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3512]
### Apache Hop version?

2.7

### Java version?

17

### Operating system

Windows

### What happened?

2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Prepared statement : INSERT INTO main.book_data (author, publisher, genre, title, publish_date) VALUES ( ?,  ?,  ?,  ?,  ?)
2023/12/21 17:51:47 - duckdb - Rollback on database connection [duckdb]
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - ERROR: Because of an error, this transform can't continue:
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - ERROR: org.apache.hop.core.exception.HopException: 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Error inserting row into table [book_data] with values: [Ms. Damion Feest], [Carlton Books], [Biography/Autobiography], [From Here to Eternity], [1981-03-23 12:26:15]
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - offending row : [author String(150)], [publisher String(150)], [genre String(150)], [title String(150)], [publish_date Date]
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Error setting value #5 [Date] on prepared statement
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - setTimestamp
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.writeToTable(TableOutput.java:383)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.processRow(TableOutput.java:117)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at java.base/java.lang.Thread.run(Thread.java:840)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Caused by: org.apache.hop.core.exception.HopDatabaseException: 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - offending row : [author String(150)], [publisher String(150)], [genre String(150)], [title String(150)], [publish_date Date]
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Error setting value #5 [Date] on prepared statement
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - setTimestamp
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.core.database.Database.setValues(Database.java:922)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.pipeline.transforms.tableoutput.TableOutput.writeToTable(TableOutput.java:250)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	... 3 more
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Caused by: org.apache.hop.core.exception.HopDatabaseException: 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Error setting value #5 [Date] on prepared statement
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - setTimestamp
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5693)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.core.database.Database.setValue(Database.java:905)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.core.database.Database.setValues(Database.java:920)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	... 4 more
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Caused by: java.sql.SQLFeatureNotSupportedException: setTimestamp
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.duckdb.DuckDBPreparedStatement.setTimestamp(DuckDBPreparedStatement.java:770)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.setPreparedStatementValue(ValueMetaBase.java:5644)
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - 	... 6 more
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Signaling 'output done' to 0 output rowsets.
2023/12/21 17:51:47 - write book data - prepared statement setTimedate() for duckdb fails.0 - Signaling 'output done' to 0 output rowsets.
2023/12/21 17:51:47 - duckdb - Rollback on database connection [duckdb]
2023/12/21 17:51:47 - duckdb - Commit on database connection [duckdb]
2023/12/21 17:51:47 - duckdb - Connection to database closed!

The outgoing data would have looked like this.
![image](https://github.com/apache/hop/assets/1233654/0c7abf1f-37b2-4fad-ab39-0a88e003296d)

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by usbrandon** [comment]
[inserting_dates_for_duckdb_fail.zip](https://github.com/apache/hop/files/13746934/inserting_dates_for_duckdb_fail.zip)
Reproduction pipeline attached
