### ISSUE TITLE
[Bug]: Formula - Search function error

### ISSUE THREAD

**Issue by Fjelley85** [apache/hop#3573]
### Apache Hop version?

2.7.0

### Java version?

11.0.19

### Operating system

Windows

### What happened?

When I'm running a bigger pipeline. I'm getting this strange error on the Search function in Formula.

---------------
024/01/24 13:18:33 - Formula 3.0 - ERROR: Unexpected error
2024/01/24 13:18:33 - Formula 3.0 - ERROR: org.apache.hop.core.exception.HopException: 
2024/01/24 13:18:33 - Formula 3.0 - Formula 'SEARCH("Norge",[dim_employee_tk])' could not not be parsed 
2024/01/24 13:18:33 - Formula 3.0 - 
2024/01/24 13:18:33 - Formula 3.0 - Unexpected conversion error while converting value [null String] to an Integer
2024/01/24 13:18:33 - Formula 3.0 - 
2024/01/24 13:18:33 - Formula 3.0 - null String : couldn't convert String to Integer
2024/01/24 13:18:33 - Formula 3.0 - 
2024/01/24 13:18:33 - Formula 3.0 - null String : couldn't convert String to number : non-numeric character found at position 1 for value [fa]
2024/01/24 13:18:33 - Formula 3.0 - 
-------------------------------

The "fa" which it is referring to is actually another column, not a value.
Look at this screenshot
![screenshot2](https://github.com/apache/hop/assets/10757859/cd4bce81-568d-4700-965c-11f43196ce58)

I'm not able to reproduce this with a simple generate rows +  formula pipeline.

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
can you add the full stacktrace here? 
since this can't be reproduced with a simple generate rows + formula pipeline, do you use the "replace value" option in your transform, and can you check for special cases (newline chars?) that could be causing issues in your formulas?

**Comment by Fjelley85** [comment]
I've managed to recreate the error with data grid + formula.
The error happens when we have a search which hits for the first values, and then suddenly doesn't.
In the case under I'm searching for "Norge", which hits on the first two rows. And then on the third row it doesn't hit and then it tries to take the value from the column before.

This doesn't happen if I would for example search for "xxxxx" with the same data, if it never hits then the error never appears it seems like.

1) Data grid
![image](https://github.com/apache/hop/assets/10757859/69cc48fe-3e99-4292-b460-7ee8db93547b)

2)  Formula
![image](https://github.com/apache/hop/assets/10757859/81606085-470d-4db1-8afc-57397e3f97d8)


3) Error log
2024/01/25 11:09:23 - Data grid.0 - Signaling 'output done' to 1 output rowsets.
2024/01/25 11:09:23 - Data grid.0 - Finished processing (I=0, O=0, R=0, W=3, U=0, E=0)
2024/01/25 11:09:23 - Generate rows.0 - Signaling 'output done' to 0 output rowsets.
2024/01/25 11:09:23 - Generate rows.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2024/01/25 11:09:23 - Dummy (do nothing).0 - Signaling 'output done' to 1 output rowsets.
2024/01/25 11:09:23 - Dummy (do nothing).0 - Finished processing (I=0, O=0, R=3, W=3, U=0, E=0)
2024/01/25 11:09:23 - Formula.0 - ERROR: Unexpected error
2024/01/25 11:09:23 - Formula.0 - ERROR: org.apache.hop.core.exception.HopException: 
2024/01/25 11:09:23 - Formula.0 - Formula 'SEARCH("Norge",[dim_employee_tk])' could not not be parsed 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - Unexpected conversion error while converting value [null String] to an Integer
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to Integer
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to number : non-numeric character found at position 1 for value [Hei]
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.Formula.processRow(Formula.java:193)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2024/01/25 11:09:23 - Formula.0 - 	at java.base/java.lang.Thread.run(Thread.java:834)
2024/01/25 11:09:23 - Formula.0 - Caused by: org.apache.hop.core.exception.HopValueException: 
2024/01/25 11:09:23 - Formula.0 - Unexpected conversion error while converting value [null String] to an Integer
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to Integer
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to number : non-numeric character found at position 1 for value [Hei]
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.getInteger(ValueMetaBase.java:2368)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.convertData(ValueMetaBase.java:4168)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.Formula.convertDataToTargetValueMeta(Formula.java:304)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.Formula.getReturnValue(Formula.java:255)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.Formula.processRow(Formula.java:191)
2024/01/25 11:09:23 - Formula.0 - 	... 2 more
2024/01/25 11:09:23 - Formula.0 - Caused by: org.apache.hop.core.exception.HopValueException: 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to Integer
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to number : non-numeric character found at position 1 for value [Hei]
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.convertStringToInteger(ValueMetaBase.java:1504)
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.getInteger(ValueMetaBase.java:2293)
2024/01/25 11:09:23 - Formula.0 - 	... 6 more
2024/01/25 11:09:23 - Formula.0 - Caused by: org.apache.hop.core.exception.HopValueException: 
2024/01/25 11:09:23 - Formula.0 - null String : couldn't convert String to number : non-numeric character found at position 1 for value [Hei]
2024/01/25 11:09:23 - Formula.0 - 
2024/01/25 11:09:23 - Formula.0 - 	at org.apache.hop.core.row.value.ValueMetaBase.convertStringToInteger(ValueMetaBase.java:1496)
2024/01/25 11:09:23 - Formula.0 - 	... 7 more
2024/01/25 11:09:23 - Table input.0 - Signaling 'output done' to 1 output rowsets.
2024/01/25 11:09:23 - Table input.0 - Finished reading query, closing connection.
2024/01/25 11:09:23 - soprasteria - Commit on database connection [soprasteria]

**Comment by Fjelley85** [comment]
Just want to add that it does not fail i when the "Hei" column is an integer, because then it doesn't produce a convert error.
Then it just copies the integer/number that is in "Hei"

**Comment by hansva** [comment]
As a project, we do not provide timelines for individual tickets.
It depends on when one of the volunteers is interested and has time to do the work.
There are parties that provide commercial support or development.
You can find a list of these parties [here](https://hop.apache.org/community/commercial/index.html)

**Comment by hansva** [comment]
fixed with #6144
