### ISSUE TITLE
[Bug]: The script transform randomly fails while obtaining scripting language

### ISSUE THREAD

**Issue by fraserward** [apache/hop#3729]
### Apache Hop version?

2.7.0

### Java version?

opernjdk 11.0.22

### Operating system

Linux

### What happened?

I run the same code every few hours and 95% of the time it works, but 5% of the time I get an error on the script transform about loading the engine.  This is with both python and EMCAScript language as the script engine.

_ERROR: Error obtaining scripting engine for language ECMAScript
ERROR: java.util.ConcurrentModificationException
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
 at org.apache.hop.pipeline.transforms.script.ScriptUtils.populateEngineFactoryMap(ScriptUtils.java:117)
 at org.apache.hop.pipeline.transforms.script.ScriptUtils.getScriptEngineManager(ScriptUtils.java:94)
 at org.apache.hop.pipeline.transforms.script.ScriptUtils.populateEngineFactoryMap(ScriptUtils.java:112)
 at org.apache.hop.pipeline.transforms.script.ScriptUtils.createNewScriptEngineByLanguage(ScriptUtils.java:59)
 at org.apache.hop.pipeline.transforms.script.Script.init(Script.java:691)
 at org.apache.hop.pipeline.transform.TransformInitThread.run(TransformInitThread.java:66)
 at java.base/java.lang.Thread.run(Thread.java:829_

and 

_ERROR: Error obtaining scripting engine for language python
ERROR: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
        at org.apache.hop.pipeline.transforms.script.ScriptUtils.populateEngineFactoryMap(ScriptUtils.java:117)
        at org.apache.hop.pipeline.transforms.script.ScriptUtils.getScriptEngineManager(ScriptUtils.java:94)
        at org.apache.hop.pipeline.transforms.script.ScriptUtils.populateEngineFactoryMap(ScriptUtils.java:112)
        at org.apache.hop.pipeline.transforms.script.ScriptUtils.createNewScriptEngineByLanguage(ScriptUtils.java:59)
        at org.apache.hop.pipeline.transforms.script.Script.init(Script.java:691)
        at org.apache.hop.pipeline.transform.TransformInitThread.run(TransformInitThread.java:66)
        at java.base/java.lang.Thread.run(Thread.java:829)_

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
[3729-concurrent-exception-in-scripts.hpl.txt](https://github.com/apache/hop/files/14666247/3729-concurrent-exception-in-scripts.hpl.txt)
