### ISSUE TITLE
[Bug]: Unable to open dialog for "Simple Mapping (sub-pipeline)" transform

### ISSUE THREAD

**Issue by fdelprete** [apache/hop#3809]
### Apache Hop version?

2.8.0

### Java version?

18.0.1.1

### Operating system

macOS

### What happened?

Create a new pipeline.
Add a Simple Mapping transform.
Edit the Simple Mapping transform.
A dialog opens with the title "Unable to open dialog for this transform"
In the dialog body you have:
NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
Root cause: NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null.

Clicking on the Details button:
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1144)
	at org.apache.hop.pipeline.transforms.mapping.SimpleMappingDialog.getData(SimpleMappingDialog.java:366)
	at org.apache.hop.pipeline.transforms.mapping.SimpleMappingDialog.open(SimpleMappingDialog.java:298)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:174)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3400)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseUp(HopGuiPipelineGraph.java:947)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4646)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1547)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1532)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1325)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4413)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3989)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:473)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:351)

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by hansva** [comment]
confirmed
.take-issue
