### ISSUE TITLE
[Bug]: After an import from PDI, the run configuration for workflow tasks are not set in a workflow

### ISSUE THREAD

**Issue by Hymmen** [apache/hop#3814]
### Apache Hop version?

2.6, 2.7, 2.8

### Java version?

openjdk version "17.0.8" 2023-07-18

### Operating system

Windows

### What happened?

The import process for PDI does not set the run configuration for workflow tasks in a workflow.
When running an imported workflow with workflow actions an error occurs at each workflow action, because the line "<run_configuration>local</run_configuration>" is missing in the task. It gives the following error:

<transformation> - ERROR: Error running action 'workflow' :
<transformation> - ERROR: org.apache.hop.core.exception.HopException: 
<transformation> - You need to specify a workflow run configuration to execute this workflow
<transformation> - 
<transformation> - 	at org.apache.hop.workflow.engine.WorkflowEngineFactory.createWorkflowEngine(WorkflowEngineFactory.java:43)
<transformation> - 	at org.apache.hop.workflow.actions.workflow.ActionWorkflow.execute(ActionWorkflow.java:445)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:655)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:798)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:798)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:798)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:798)
<transformation> - 	at org.apache.hop.workflow.Workflow.executeFromStart(Workflow.java:456)
<transformation> - 	at org.apache.hop.workflow.Workflow.startExecution(Workflow.java:300)
<transformation> - 	at org.apache.hop.workflow.engines.local.LocalWorkflowEngine.startExecution(LocalWorkflowEngine.java:249)
<transformation> - 	at org.apache.hop.ui.hopgui.file.workflow.HopGuiWorkflowGraph.lambda$start$9(HopGuiWorkflowGraph.java:3683)
<transformation> - 	at java.base/java.lang.Thread.run(Thread.java:833)

Right now, you have to edit each task and close it with OK to truly set the run configuration for the task.

### Issue Priority

Priority: 3

### Issue Component

Component: Import

**Comment by Hymmen** [comment]
Often <logext/> and <logfile/> get added too.

**Comment by nadment** [comment]
This probably depends on the imported version of PDI. The Hop importer replaces the "run_configuration" element, which does not exist for Job entry (PDI V7).

Job entry (PDI 7)
![image](https://github.com/user-attachments/assets/72d05f40-0ab8-477c-a7c6-2a53978facd6)

Job entry (PDI V9 )
![image](https://github.com/user-attachments/assets/5b044a78-90dc-42a1-8b10-35c4a21ba64c)

**Comment by gmitter-ef** [comment]
Reproduced the problem using Apache Hop 2.11.0 Windows version when importing projects from PDI 9.3.0.0.

**Comment by bamaer** [comment]
.take-issue
