### ISSUE TITLE
[Bug]: Converting Date to String using Select values Meta-data Tab not working on Linux

### ISSUE THREAD

**Issue by Zusammenarbeit-GIP-RZV** [apache/hop#3893]
### Apache Hop version?

2.8

### Java version?

openjdk11-jre

### Operating system

Docker

### What happened?

I tried to execute a converted Pipeline (converted from kettle) using your apache/hop:latest Docker Image.
But it is failing on this image, and not on my windows machine.
I attached a simplified example. I use "Get system info" to get the "System date (fixed)" and want to convert it to a String with a specific format. Usually I do this using the "Select values" transforms "Meta-data" Tab. But this Step is failing with the following error:
`2024/04/29 07:23:05 - test - Error storing execution data
2024/04/29 07:23:05 - test - date_fixed Date : There was a data type error: the data type of java.lang.String object [20240429072305] does not correspond to value meta [Date] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2024/04/29 07:23:05 - test -
2024/04/29 07:23:05 - test -    at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:342)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.stopTransformExecutionInfoTimer(LocalPipelineEngine.java:509)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.engines.local.LocalPipelineEngine.pipelineCompleted(LocalPipelineEngine.java:465)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.Pipeline.firePipelineExecutionFinishedListeners(Pipeline.java:1339)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.Pipeline.lambda$startThreads$0(Pipeline.java:1142)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.transform.BaseTransform.fireTransformFinishedListeners(BaseTransform.java:2825)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.transform.BaseTransform.markStop(BaseTransform.java:2814)
2024/04/29 07:23:05 - test -    at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:142)
2024/04/29 07:23:05 - test -    at java.base/java.lang.Thread.run(Thread.java:829)
2024/04/29 07:23:05 - test - Caused by: com.fasterxml.jackson.databind.JsonMappingException: date_fixed Date : There was a data type error: the data type of java.lang.String object [20240429072305] does not correspond to value meta [Date] (through reference chain: org.apache.hop.execution.ExecutionData["rowsBinaryGzipBase64Encoded"])
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:323)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:780)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1572)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1273)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
2024/04/29 07:23:05 - test -    at org.apache.hop.execution.local.FileExecutionInfoLocation.registerData(FileExecutionInfoLocation.java:339)
2024/04/29 07:23:05 - test -    ... 8 more
2024/04/29 07:23:05 - test - Caused by: java.lang.RuntimeException: date_fixed Date : There was a data type error: the data type of java.lang.String object [20240429072305] does not correspond to value meta [Date]
2024/04/29 07:23:05 - test -    at org.apache.hop.core.row.value.ValueMetaBase.writeData(ValueMetaBase.java:3106)
2024/04/29 07:23:05 - test -    at org.apache.hop.core.row.RowMeta.writeData(RowMeta.java:717)
2024/04/29 07:23:05 - test -    at org.apache.hop.execution.ExecutionData.getRowsBinaryGzipBase64Encoded(ExecutionData.java:190)
2024/04/29 07:23:05 - test -    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024/04/29 07:23:05 - test -    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024/04/29 07:23:05 - test -    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024/04/29 07:23:05 - test -    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
2024/04/29 07:23:05 - test -    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:772)
2024/04/29 07:23:05 - test -    ... 15 more`

[Conversion Error Example.zip](https://github.com/apache/hop/files/15146245/Conversion.Error.Example.zip)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
your pipeline probably runs just fine, the error comes from the execution information location that we seem to have active in the container.

**Comment by flotho** [comment]
same thing for me with strings

**Comment by hansva** [comment]
It's linked to #2312 I explained the cause of the error in a reply there.
https://github.com/apache/hop/issues/2312#issuecomment-2310374167

Will try and free up some time to tackle it

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
should have been resolved along the way
