### ISSUE TITLE
[Bug]: Review UserDefinedJavaClass transfo error messages (use “StepMetaInterface”)

### ISSUE THREAD

**Issue by nadment** [apache/hop#4138]
### Apache Hop version?

2.10.0-SNAPSHOT

### Java version?

Java 11

### Operating system

Windows

### What happened?

I have a source code with an error, but when we execute the pipeline, the message is not clear with the word “StepMetaInterface”.

2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - ERROR: Unable to get fields from previous transforms because of an error
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - ERROR: org.apache.hop.core.exception.HopTransformException: 
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - Error initializing UserDefinedJavaClass to get fields: 
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - Line 12, Column 26: Line 12, Column 26: Cannot determine simple type name "StepMetaInterface"
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta.getFields(UserDefinedJavaClassMeta.java:573)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at org.apache.hop.pipeline.transform.BaseTransformMeta.getFields(BaseTransformMeta.java:324)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at org.apache.hop.pipeline.PipelineMeta.getThisTransformFields(PipelineMeta.java:1401)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at org.apache.hop.pipeline.PipelineMeta.getThisTransformFields(PipelineMeta.java:1343)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassDialog.lambda$open$4(UserDefinedJavaClassDialog.java:475)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - 	at java.base/java.lang.Thread.run(Unknown Source)
2024/07/17 10:49:12 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@2042a26f - Caused by: org.codehaus.commons.compiler.CompileException: Line 12, Column 26: Line 12, Column 26: Cannot determine simple type name "StepMetaInterface"
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - ERROR: Unable to get fields from previous transforms because of an error
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - ERROR: org.apache.hop.core.exception.HopTransformException: 
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - Error initializing UserDefinedJavaClass to get fields: 
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - Line 12, Column 26: Line 12, Column 26: Cannot determine simple type name "StepMetaInterface"
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta.getFields(UserDefinedJavaClassMeta.java:573)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.transform.BaseTransformMeta.getFields(BaseTransformMeta.java:324)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.PipelineMeta.getThisTransformFields(PipelineMeta.java:1401)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1209)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1186)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1103)
2024/07/17 10:49:22 - org.apache.hop.pipeline.transforms.userdefinedjavaclass.UserDefinedJavaClassMeta@6e9f587 - 	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1069)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Impossible to reproduce
