### ISSUE TITLE
[Bug]: Dimension Lookup & Update Transform SQL Button Nullpointer Exception

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#4153]
### Apache Hop version?

2.9.0

### Java version?

11

### Operating system

Windows

### What happened?

While trying to generate the SQL script from HOP's Dimension Lookup and Update Transform, we get null pointer exception error message. As shown below: 

![Dimension Lookup and Update - SQL Button Bug](https://github.com/user-attachments/assets/72c1e9c6-62e1-40fd-9560-9cebfe0c245d)

**Database Used:** Postgres 16
**Stacktrace:** 
java.lang.NullPointerException
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta.getSqlStatements(DimensionLookupMeta.java:838)
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupDialog.create(DimensionLookupDialog.java:1608)
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupDialog.lambda$open$11(DimensionLookupDialog.java:385)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:522)
	at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupDialog.open(DimensionLookupDialog.java:424)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:173)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3420)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:2233)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:95)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:182)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:475)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
could you specify the database type you are using as it might be related.

**Comment by nadment** [comment]
Could you provide also a stack trace (using the Details button)?

**Comment by kirana-ks** [comment]
Updated the ticket with the details.
