### ISSUE TITLE
[Bug]: java.lang.NoSuchMethodError: with log4j

### ISSUE THREAD

**Issue by nadment** [apache/hop#4183]
### Apache Hop version?

2.10.0-SNAPSHOT

### Java version?

Java 17

### Operating system

Windows

### What happened?

Download the last build: hop-client-2.10.0-20240731.160840-1.zip
Unzip in a new folder
and run hop-gui.bat throw exception

Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Object org.apache.logging.log4j.util.LoaderUtil.newCheckedInstanceOfProperty(java.lang.String, java.lang.Class, java.util.function.Supplier)'
        at org.apache.logging.log4j.core.config.LoggerConfig.<clinit>(LoggerConfig.java:84)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:139)
        at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
        at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:76)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:263)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:222)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:140)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:149)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:46)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
        at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
        at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
        at org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:46)
        at org.apache.commons.logging.LogFactoryService.getInstance(LogFactoryService.java:41)
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:657)
        at org.apache.commons.vfs2.impl.DefaultFileSystemManager.<init>(DefaultFileSystemManager.java:159)
        at org.apache.hop.core.vfs.HopVfs.createFileSystemManager(HopVfs.java:131)
        at org.apache.hop.core.vfs.HopVfs.getFileSystemManager(HopVfs.java:70)
        at org.apache.hop.core.vfs.HopVfs.getFileObject(HopVfs.java:248)
        at org.apache.hop.core.config.ConfigFileSerializer.readFromFile(ConfigFileSerializer.java:78)
        at org.apache.hop.core.config.plugin.ConfigFile.readFromFile(ConfigFile.java:73)
        at org.apache.hop.core.config.HopConfig.<init>(HopConfig.java:47)
        at org.apache.hop.core.config.HopConfig.getInstance(HopConfig.java:55)
        at org.apache.hop.core.config.HopConfig.readOption(HopConfig.java:82)
        at org.apache.hop.core.config.HopConfig.readOptionString(HopConfig.java:91)

### Issue Priority

Priority: 3

### Issue Component

Component: Other

**Comment by hansva** [comment]
.take-issue
