### ISSUE TITLE
[Bug]: Oracle Bulk Loader: Invalid argument for username/password

### ISSUE THREAD

**Issue by DaniLecx** [apache/hop#4322]
### Apache Hop version?

2.9.0

### Java version?

openjdk-22.0.2

### Operating system

Windows

### What happened?

I'm using Oracle bulk loader to load data from a csv file generated by text file output.
Unfortunately I'm getting two Oracle errors depending on my DB connection:

1. ORA-12545: Connect failed because target host or object does not exist

      When using TNS format in Manual connection URL

      Here's log:

      Error while executing sqlldr 'C:\Oracle\product\client_18.0.0\x86\bin\sqlldr.exe control=control.ctl' log='log.log' userid=user/**@'

      Note there's nothing after @ in userid parameter, it's empty.

2. SQL*Loader-101: Invalid argument for username/password

      When using Server host name + Port + Database name

      Here's log:

      Error while executing sqlldr 'C:\Oracle\product\client_18.0.0\x86\bin\sqlldr.exe control=control.ctl' log='log.log' userid=user/**@hostname:1521DBName'

      Note there's no / between the port and Database name.

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
.take-issue

**Comment by bamaer** [comment]
additional issues: 
- connection line is not visible in 2.10.0-SNAPSHOT-20240918 
- NPE when trying to get SQL statements to create or update a table: 
```
java.lang.NullPointerException: Cannot invoke "org.apache.hop.pipeline.PipelineMeta.findDatabase(String, org.apache.hop.core.variables.IVariables)" because the return value of "org.apache.hop.pipeline.transform.TransformMeta.getParentPipelineMeta()" is null
	at org.apache.hop.pipeline.transforms.orabulkloader.OraBulkLoaderMeta.getSqlStatements(OraBulkLoaderMeta.java:550)
	at org.apache.hop.pipeline.transforms.orabulkloader.OraBulkLoaderDialog.create(OraBulkLoaderDialog.java:1383)
	at org.apache.hop.pipeline.transforms.orabulkloader.OraBulkLoaderDialog.lambda$open$3(OraBulkLoaderDialog.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1392)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:528)
	at org.apache.hop.pipeline.transforms.orabulkloader.OraBulkLoaderDialog.open(OraBulkLoaderDialog.java:960)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:195)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3419)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseUp(HopGuiPipelineGraph.java:965)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:237)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1392)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4427)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4003)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)
```
