### ISSUE TITLE
[Bug]: DimensionLookup transform fails with hop-run

### ISSUE THREAD

**Issue by nadment** [apache/hop#4328]
### Apache Hop version?

2.10.0-SNAPSHOT

### Java version?

Java 17

### Operating system

Windows

### What happened?

Step to reproduce: 
1. Disabled "Update the dimension" and try to retrieve a lookup field
2. Then execute with hop-run.

2024/08/02 13:57:46 - org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta@46dcc86 - Unable to retrieve data type of return fields because of an unexpected error
2024/08/02 13:57:46 - org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookupMeta@46dcc86 - Cannot invoke "org.apache.hop.core.row.IRowMeta.searchValueMeta(String)" because "extraFields" is null
org.apache.hop.core.exception.HopTransformException:
Lookup field [FIELD_CONFORMED] couldn't be found!
    at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:152)
    at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:54)
    at java.base/java.lang.Thread.run(Unknown Source)

I didn't understand why the transformation works well with hop-gui and doesn't work with hop-run, but by cleaning up the code I found a solution so that it works in both cases.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Run, Component: Transforms

**Comment by nadment** [comment]
Possibly the same issue #3546
