### ISSUE TITLE
[Bug]: NullPointer Exception at FakeData Tranformation

### ISSUE THREAD

**Issue by vdwals** [apache/hop#4341]
### Apache Hop version?

2.9.0 (2024-05-20 11.41.51)

### Java version?

21.0.4

### Operating system

Windows

### What happened?

1. Create a Pipeline
2. Add Fake Data Transformation
3. Set one colum to field name of your choise and select Company/domainName in column 2 and 3
4. Try preview of data
5. See Exception with Details:
`java.lang.NullPointerException: Cannot invoke "org.apache.hop.core.logging.ILogChannel.logError(String, java.lang.Throwable)" because "this.log" is null
	at org.apache.hop.pipeline.transforms.fake.FakeMeta.getFields(FakeMeta.java:111)
	at org.apache.hop.pipeline.transform.BaseTransformMeta.getFields(BaseTransformMeta.java:324)
	at org.apache.hop.pipeline.PipelineMeta.getThisTransformFields(PipelineMeta.java:1395)
	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1203)
	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1097)
	at org.apache.hop.pipeline.PipelineMeta.getTransformFields(PipelineMeta.java:1063)
	at org.apache.hop.ui.pipeline.debug.PipelineDebugDialog.showTransformDebugInformation(PipelineDebugDialog.java:449)
	at org.apache.hop.ui.pipeline.debug.PipelineDebugDialog.refreshTransformList(PipelineDebugDialog.java:307)
	at org.apache.hop.ui.pipeline.debug.PipelineDebugDialog.getData(PipelineDebugDialog.java:260)
	at org.apache.hop.ui.pipeline.debug.PipelineDebugDialog.open(PipelineDebugDialog.java:242)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineRunDelegate.executePipeline(HopGuiPipelineRunDelegate.java:165)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.preview(HopGuiPipelineGraph.java:3573)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.hop.core.gui.plugin.action.GuiActionLambdaBuilder.lambda$createLambda$0(GuiActionLambdaBuilder.java:95)
	at org.apache.hop.ui.hopgui.context.GuiContextUtil.lambda$handleActionSelection$0(GuiContextUtil.java:182)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:475)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)
`

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
PR #4347 will fix this issue
