### ISSUE TITLE
[Bug]: Darkmode - Settings Panel does not show tabs

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#4611]
### Apache Hop version?

2.11-SNAPSHOT

### Java version?

Java 17

### Operating system

Linux

### What happened?

![image](https://github.com/user-attachments/assets/d51bf336-8a5b-4b7c-9e52-c511d59ffc0f)

I am running Ubuntu 22.04 (Pop OS!).  Dark Mode ends up having the tabs not showing. 

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by usbrandon** [comment]
Error in the Hop GUI : Argument not valid
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:876)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:859)
	at org.eclipse.swt.custom.CTabFolderRenderer.drawUnselected(CTabFolderRenderer.java:1648)
	at org.eclipse.swt.custom.CTabFolderRenderer.draw(CTabFolderRenderer.java:646)
	at org.eclipse.swt.custom.CTabFolder.onPaint(CTabFolder.java:2094)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:337)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3877)
	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:396)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:506)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2570)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6842)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)

**Comment by hansva** [comment]
I have a feeling all the tickets with SWT errors you have created will be linked to each other. Does your new distro use wayland in stead of x11 per chance ?

**Comment by hansva** [comment]
What does echo "$XDG_SESSION_TYPE" return ?

**Comment by usbrandon** [comment]
x11
![image](https://github.com/user-attachments/assets/08bb84b9-aa22-4f96-a9dd-82d88c9561b3)
