### ISSUE TITLE
[Bug]: SWT errors when running workflows and pipelines

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#4615]
### Apache Hop version?

2.11-SNAPSHOT

### Java version?

Java 17

### Operating system

Linux

### What happened?

When running a workflow, the log window reflects a lot of GUI errors relating to SWT
![image](https://github.com/user-attachments/assets/dd4b1229-ec8d-4c36-a0b7-e5e2cb89b45c)

2024/11/23 09:54:10 - Hop - Projects enabled
2024/11/23 10:05:55 - GUI - ERROR: Unable to call method editMetadataElement in class org.apache.hop.ui.core.widget.MetaSelectionLine : null
2024/11/23 10:05:55 - GUI - ERROR: java.lang.reflect.InvocationTargetException
2024/11/23 10:05:55 - GUI - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024/11/23 10:05:55 - GUI - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024/11/23 10:05:55 - GUI - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024/11/23 10:05:55 - GUI - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:213)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)
2024/11/23 10:05:55 - GUI - Caused by: java.lang.IllegalArgumentException: Argument not valid
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.SWT.error(SWT.java:4903)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.SWT.error(SWT.java:4837)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.SWT.error(SWT.java:4808)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.graphics.GC.drawImage(GC.java:876)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.graphics.GC.drawImage(GC.java:859)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.custom.CTabFolderRenderer.drawUnselected(CTabFolderRenderer.java:1648)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.custom.CTabFolderRenderer.draw(CTabFolderRenderer.java:646)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.custom.CTabFolder.onPaint(CTabFolder.java:2094)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:337)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3877)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:396)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:506)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2570)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6842)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:2995)
2024/11/23 10:05:55 - GUI - 	at org.eclipse.swt.widgets.Shell.open(Shell.java:2050)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:522)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.dialog.ErrorDialog.showErrorDialog(ErrorDialog.java:180)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.dialog.ErrorDialog.<init>(ErrorDialog.java:79)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.metadata.MetadataManager.newMetadata(MetadataManager.java:410)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.widget.MetaSelectionLine.newMetadata(MetaSelectionLine.java:301)
2024/11/23 10:05:55 - GUI - 	at org.apache.hop.ui.core.widget.MetaSelectionLine.editMetadataElement(MetaSelectionLine.java:237)
2024/11/23 10:05:55 - GUI - 	... 12 more
2024/11/23 10:18:09 - Hop - Starting workflow
2024/11/23 10:18:09 - starting_place - Start of workflow execution
2024/11/23 10:18:09 - starting_place - Starting action [generate_company_data.hpl]
2024/11/23 10:18:09 - generate_company_data.hpl - Using run configuration [local]
2024/11/23 10:18:09 - generate_company_data - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
2024/11/23 10:18:09 - generate_company_data - Execution started for pipeline [generate_company_data]
2024/11/23 10:18:09 - Generate 1 row.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2024/11/23 10:18:09 - Example Company Data.0 - Finished processing (I=0, O=0, R=1, W=1, U=0, E=0)
2024/11/23 10:18:09 - Save company data to a text file.0 - Finished processing (I=0, O=2, R=1, W=1, U=0, E=0)
2024/11/23 10:18:09 - generate_company_data - Pipeline duration : 0.179 seconds [  0.179" ]
2024/11/23 10:18:09 - generate_company_data - Execution finished on a local pipeline engine with run configuration 'local'
2024/11/23 10:18:09 - starting_place - Starting action [Success]
2024/11/23 10:18:09 - starting_place - Finished action [Success] (result=[true])
2024/11/23 10:18:09 - starting_place - Finished action [generate_company_data.hpl] (result=[true])
2024/11/23 10:18:09 - starting_place - Workflow execution finished
2024/11/23 10:18:09 - Hop - Workflow execution has ended
2024/11/23 10:18:09 - starting_place - Workflow duration : 0.292 seconds [  0.292" ]

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by bamaer** [comment]
Looks like a wayland issue. Can you try with X11 and see if you can reproduce the issue there?
