### ISSUE TITLE
[Bug]: After running a workflow, if you try to open a pipeline action on the canvas, SWT errors are thrown.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#4616]
### Apache Hop version?

2.11-SNAPSHOT

### Java version?

Java 17

### Operating system

Linux

### What happened?

![image](https://github.com/user-attachments/assets/96d0dc9d-e5a6-4663-b982-3f6282247eb3)

java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:876)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:859)
	at org.eclipse.swt.custom.CTabFolderRenderer.drawUnselected(CTabFolderRenderer.java:1648)
	at org.eclipse.swt.custom.CTabFolderRenderer.draw(CTabFolderRenderer.java:646)
	at org.eclipse.swt.custom.CTabFolder.onPaint(CTabFolder.java:2094)
	at org.eclipse.swt.custom.CTabFolder.lambda$0(CTabFolder.java:337)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1643)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1626)
	at org.eclipse.swt.widgets.Control.gtk_draw(Control.java:3877)
	at org.eclipse.swt.widgets.Scrollable.gtk_draw(Scrollable.java:396)
	at org.eclipse.swt.widgets.Composite.gtk_draw(Composite.java:506)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2570)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6842)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6162)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_do_event(Native Method)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1598)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
	at org.apache.hop.ui.core.dialog.BaseDialog.defaultShellHandling(BaseDialog.java:528)
	at org.apache.hop.workflow.actions.pipeline.ActionPipelineDialog.open(ActionPipelineDialog.java:93)
	at org.apache.hop.ui.hopgui.file.workflow.delegates.HopGuiWorkflowActionDelegate.editAction(HopGuiWorkflowActionDelegate.java:300)
	at org.apache.hop.ui.hopgui.file.workflow.HopGuiWorkflowGraph.editAction(HopGuiWorkflowGraph.java:2968)
	at org.apache.hop.ui.hopgui.file.workflow.HopGuiWorkflowGraph.mouseUp(HopGuiWorkflowGraph.java:792)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:237)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by bamaer** [comment]
Looks like a wayland issue. Can you try with X11 and see if you can reproduce the issue there?
