### ISSUE TITLE
[Bug]: Error opening workflow with an Xslt action

### ISSUE THREAD

**Issue by nadment** [apache/hop#4628]
### Apache Hop version?

2.11

### Java version?

Java 17

### Operating system

Windows

### What happened?

Error setting value on field 'ifFileExists' using method 'setIfFileExists' in class 'org.apache.hop.workflow.actions.xml.xslt.Xslt
org.apache.hop.workflow.actions.xml.xslt.Xslt.setIfFileExists(int)

	at org.apache.hop.ui.hopgui.file.workflow.HopWorkflowFileType.openFile(HopWorkflowFileType.java:173)
	at org.apache.hop.ui.hopgui.perspective.explorer.ExplorerPerspective.openFile(ExplorerPerspective.java:737)
	at org.apache.hop.ui.hopgui.perspective.explorer.ExplorerPerspective.openFile(ExplorerPerspective.java:720)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4326)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1174)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4124)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3712)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)
Caused by: org.apache.hop.core.exception.HopXmlException: 
Unable to load the workflow from XML file [config/projects/default/All-Actions.hwf]

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by bamaer** [comment]
.take-issue
