### ISSUE TITLE
[Bug]: NullPointerException in hop/registerPipeline Rest API when log_file flag is enabled

### ISSUE THREAD

**Issue by chaturvedakanksha** [apache/hop#4677]
### Apache Hop version?

2.7.0

### Java version?

22.0.2

### Operating system

Windows

### What happened?

When invoking the hop/registerPipeline REST API with the payload provided below, the API throws a NullPointerException if the log_file flag is set to Y and a log_filename is specified.

The specified log file gets created in the container, but the exception occurs afterward, halting further execution.

Error Details:
Exception Message:
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at org.apache.hop.core.logging.LoggingRegistry.registerLogChannelFileWriterBuffer(LoggingRegistry.java:261)
	at org.apache.hop.core.logging.LogChannelFileWriter.<init>(LogChannelFileWriter.java:74)
	at org.apache.hop.core.logging.LogChannelFileWriter.<init>(LogChannelFileWriter.java:87)
	at org.apache.hop.www.BaseWorkflowServlet.createPipeline(BaseWorkflowServlet.java:146)
	at org.apache.hop.www.RegisterPipelineServlet.generateBody(RegisterPipelineServlet.java:56)

Steps to Reproduce:
1. Start the Apache Hop server using the provided Docker script:
docker run -it --rm \
  --env HOP_SERVER_USER=admin \
  --env HOP_SERVER_PASS=admin \
  --env HOP_SERVER_SHUTDOWNPORT=8080 \
  --env HOP_SERVER_PORT=8181 \
  --env HOP_SERVER_HOSTNAME=0.0.0.0 \
  -p 8080:8080 \
  -p 8181:8181 \
  --name my-hop-server-container \
  apache/hop:2.7.0

2. Make a POST request to hop/registerPipeline REST API with the following payload:
<pipeline_configuration>
    ...
    <log_file>Y</log_file>
    <log_filename>/tmp/generateRowsLog.log</log_filename>
    ...
</pipeline_configuration>

3. Observe that the log file is created inside the container, but a NullPointerException is thrown during the pipeline registration process.

Attached full xml payload
[payload.txt](https://github.com/user-attachments/files/18037540/payload.txt)

**Expected Behavior**:
The pipeline should register successfully, and logs should be written to the specified file without errors.

![image](https://github.com/user-attachments/assets/845e8160-666c-4277-9b34-167fec2951aa)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by chaturvedakanksha** [comment]
1. In BaseWorkflowServlet.java, SimpleLoggingObject is created at line 118

![image](https://github.com/user-attachments/assets/69d4c756-fc40-455b-9d52-cbf68520fff0)

2. Which further creating LogChannelFileWriter at line 143, serveletLoggingObject is used to get log channel Id which is of type SimpleLoggingObject.

![image](https://github.com/user-attachments/assets/46d9b0e4-0feb-4f07-a2a1-b4a2a9a6aecf)

3. SimpleLoggingObject class return LogChannelId as null at line 88

![image](https://github.com/user-attachments/assets/2c2728c3-6de0-454f-b0f4-82d077b273cf)

4. Above LogChannelFileWriter if furter send to registerLogChannelFileWriterBuffer which is using Log Channel Id as key thus further throwing null pointer exception at line 261

![image](https://github.com/user-attachments/assets/7d0e9e21-3974-4b06-be40-3eeae5f7cefe)

**Comment by hansva** [comment]
.take-issue
