### ISSUE TITLE
[Bug]: Hop GUI - can't configure Table Input transform with a JTDS-driven database

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4719]
### Apache Hop version?

2.11.0

### Java version?

17.0.2

### Operating system

Linux

### What happened?

Have a Table Input transform in a pipeline configured to interact with a JTDS-driven database (usually Microsoft SQL Server).

When trying to open the dialog, the following error appears:
```
Unable to open dialog for this transform
java.lang.AbstractMethodError
	at net.sourceforge.jtds.jdbc.JtdsDatabaseMetaData.getFunctions(JtdsDatabaseMetaData.java:3570)
	at org.apache.hop.pipeline.transforms.tableinput.TableInputDialog.getSqlReservedWords(TableInputDialog.java:384)
	at org.apache.hop.pipeline.transforms.tableinput.TableInputDialog.open(TableInputDialog.java:346)
	at org.apache.hop.ui.hopgui.file.pipeline.delegates.HopGuiPipelineTransformDelegate.editTransform(HopGuiPipelineTransformDelegate.java:195)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.editTransform(HopGuiPipelineGraph.java:3368)
	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph.mouseUp(HopGuiPipelineGraph.java:940)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:237)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:476)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:354)
```

No further details are provided when pressing the "Details" button.

**_Marked as P1 for regression: issue is not present on version 2.10.0_**

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by jasontang0920** [comment]
Consider using the Microsoft JDBC Driver (Recommended):

Due to the slower maintenance and updates of jTDS, it is highly recommended to use the official Microsoft JDBC driver, as it offers better support for SQL Server.

You need to download mssql-jdbc-<version>.jar from the Microsoft website and place it in Hop's lib directory.

It worked for me.

**Comment by hansva** [comment]
Could you test if this still happens with a latest build, this build should be available in about 2-3 hours [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.12.0-SNAPSHOT/)

**Comment by hansva** [comment]
.take-issue

**Comment by dave-csc** [comment]
> Could you test if this still happens with a latest build, this build should be available in about 2-3 hours [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.12.0-SNAPSHOT/)

Tried with today's snapshot, the configuration window opens correctly ✌

**Comment by hansva** [comment]
thanks for testing @dave-csc !

**Comment by soeynhausenFSB** [comment]
Sorry for beeing late. Today I tested the issue in the current snapshot as well. Thank you so much for the very fast solution!
