### ISSUE TITLE
[Bug]: An error occurred during Kafka Consumer transform error handling

### ISSUE THREAD

**Issue by petertsneg** [apache/hop#4750]
### Apache Hop version?

2.11

### Java version?

17.0.12.7

### Operating system

Windows

### What happened?

1.create workflow
![image](https://github.com/user-attachments/assets/8184e37e-69cc-44b6-a6fd-76293351a473)
2.Create a pipeline and insert the Kafka Consumer Transform. Set error handling
![image](https://github.com/user-attachments/assets/3c542ff3-56bf-446d-b3cf-a07d2fa897cd)
3.Run
![image](https://github.com/user-attachments/assets/b8b5d4af-9f84-4f1e-9e83-c7c69387bd80)

### Issue Priority

Priority: 0

### Issue Component

Component: Transforms

**Comment by vbhanuchander-lang** [comment]
This looks fixed already — it can be closed.

The stack trace in the screenshot is:

```
Unable to open pipeline: Cannot invoke "org.apache.hop.pipeline.transform.TransformMeta.getName()"
  because "nextTransform" is null
  at org.apache.hop.pipeline.transforms.kafka.consumer.KafkaConsumerInputMeta.getFields(KafkaConsumerInputMeta.java:444)
  at org.apache.hop.pipeline.transform.BaseTransformMeta.getFields(BaseTransformMeta.java:328)
  at org.apache.hop.pipeline.PipelineMeta.getThisTransformFields(PipelineMeta.java:1413)
```

`KafkaConsumerInputMeta.getFields()` checks whether it is being called down the error path by comparing the error target's name against `nextTransform`:

```java
if (transformErrorMeta != null
    && transformErrorMeta.getTargetTransform() != null
    && transformErrorMeta.getTargetTransform().getName().equals(nextTransform.getName())) {
```

`PipelineMeta.getThisTransformFields()` legitimately passes `nextTransform == null`, so with error handling configured (making `transformErrorMeta` non-null) the third condition dereferenced null and the pipeline could not be opened at all — which matches the report exactly.

A `nextTransform != null` guard was added to that condition in 52efe7a40b ("issue #7519 : Kafka Consumer stop when idle", #7524, 2026-07-15), where it came along incidentally rather than as the point of the change — which is presumably why this issue was never linked to it.

Checked the file at each release tag to confirm where the fix lands:

| tag | guarded |
|---|---|
| 2.11.0-rc1 (the reported version) | no |
| 2.13.0-rc1 | no |
| 2.15.0-rc1 | no |
| 2.17.0-rc1 | no |
| 2.18.0-rc1 | no |
| 2.19.0-rc1 | **yes** |

So the NPE is reproducible on everything up to and including 2.18.0 and is gone from 2.19.0 onwards. @petertsneg, upgrading to 2.19.0 or later should resolve it.
